/**
 * audit-form-template.ts
 * ───────────────────────
 * Template Audit complet conforme ISO 13485 8.2.4
 *
 * 6 sections - 45+ champs - logique conditionnelle - findings repeater
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const AUDIT_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-audit-001',
  documentId: 'doc-tmr-aud-001',   // Document Control approuve TMR-AUD-001
  title: 'Internal / External / Supplier Audit Report',
  version: '2.0',
  isActive: true,
  recordTarget: 'Audit',
  normReference: 'ISO 13485:2016 8.2.4 / FDA 21 CFR 820.22',
  retentionYears: 7,
  closureRequiredFields: [
    'audit_scope',
    'audit_criteria',
    'lead_auditor',
    'executive_summary',
    'findings',
    'management_response',
    'qa_approval_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Audit Planning
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s1',
      order: 1,
      title: '1. Audit Planning',
      description: 'Define the audit scope, objectives, criteria, and schedule. Ensure independence and competency of the audit team.',
      normClause: 'ISO 13485 8.2.4(a)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'audit_number',
          name: 'auditNumber',
          label: 'Audit Number',
          type: 'text',
          readOnly: true,
          helpText: 'Generated automatically',
          normClause: '4.2.4',
        },
        {
          id: 'audit_title',
          name: 'auditTitle',
          label: 'Audit Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'e.g. Internal Audit of Production Area Q1 2024',
        },
        {
          id: 'audit_type',
          name: 'auditType',
          label: 'Audit Type',
          type: 'select',
          required: true,
          options: ['Internal', 'External (Customer)', 'External (Regulatory)', 'Supplier / Vendor'],
          normClause: '8.2.4',
          helpText: 'Internal: self-assessment / External: customer or regulatory / Supplier: vendor qualification or surveillance',
        },
        {
          id: 'audit_scope',
          name: 'auditScope',
          label: 'Audit Scope',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 50 },
          helpText: 'Define the boundaries: processes, departments, products, sites, time period covered.',
          normClause: '8.2.4(a)',
          placeholder: 'This audit covers [processes/departments] at [site]. Period under review: [date range]. In scope: [items]. Out of scope: [items with justification].',
        },
        {
          id: 'audit_criteria',
          name: 'auditCriteria',
          label: 'Audit Criteria',
          type: 'multi_select',
          required: true,
          requiredForClosure: true,
          options: [
            'ISO 13485:2016',
            'FDA 21 CFR 820',
            'EU MDR 2017/745',
            'EU IVDR 2017/746',
            'MDSR (Medical Device Single Audit Program)',
            'Internal SOPs / Quality Manual',
            'Customer-specific requirements',
            'Regulatory commitments (conditions of approval)',
            'GMP Annex requirements',
            'ISO 14971 Risk Management',
            'Other',
          ],
          normClause: '8.2.4(a)',
        },
        {
          id: 'audit_objectives',
          name: 'auditObjectives',
          label: 'Audit Objectives',
          type: 'textarea',
          required: true,
          placeholder: 'e.g. Verify compliance with SOP-PROD-001, assess effectiveness of CAPA-2024-012, evaluate change control process maturity...',
          normClause: '8.2.4(a)',
        },
        {
          id: 'scheduled_date',
          name: 'scheduledDate',
          label: 'Scheduled Date(s)',
          type: 'date_range',
          required: true,
          helpText: 'Start and end dates for the audit execution',
          normClause: '8.2.4(a)',
        },
        {
          id: 'lead_auditor',
          name: 'leadAuditor',
          label: 'Lead Auditor',
          type: 'user_select',
          required: true,
          requiredForClosure: true,
          helpText: 'Must be independent of the area being audited',
          normClause: '8.2.4(b)',
        },
        {
          id: 'audit_team',
          name: 'auditTeam',
          label: 'Audit Team Members',
          type: 'repeater',
          required: true,
          columns: [
            { id: 'at_name',     label: 'Team Member',   type: 'user_select', required: true, width: 'md' },
            { id: 'at_role',     label: 'Role',           type: 'select',      required: true, width: 'sm',
              options: ['Lead Auditor', 'Co-Auditor', 'Technical Expert', 'Observer', 'Trainee'] },
            { id: 'at_scope',    label: 'Assigned Scope', type: 'text',        required: false, width: 'lg' },
          ],
          minRows: 1,
          helpText: 'List all audit team members and their assigned areas',
        },
        {
          id: 'auditees',
          name: 'auditees',
          label: 'Auditees (Key Contacts)',
          type: 'repeater',
          columns: [
            { id: 'au_name',      label: 'Auditee',       type: 'user_select', required: true, width: 'md' },
            { id: 'au_department', label: 'Department',   type: 'text',        required: true, width: 'md' },
            { id: 'au_role',      label: 'Role / Function', type: 'text',      required: false, width: 'md' },
          ],
          minRows: 1,
          helpText: 'Key contacts in the area being audited',
        },
        {
          id: 'previous_audit_reference',
          name: 'previousAuditReference',
          label: 'Previous Audit Reference',
          type: 'text',
          placeholder: 'e.g. AUD-2024-005',
          helpText: 'Reference to the previous audit of the same scope (for follow-up verification)',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Audit Checklist & Plan
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s2',
      order: 2,
      title: '2. Audit Checklist & Plan',
      description: 'Define the audit checklist items aligned with the audit criteria. Each item maps to a specific clause or requirement.',
      normClause: 'ISO 13485 8.2.4(a)',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'checklist',
          name: 'checklist',
          label: 'Audit Checklist Items',
          type: 'repeater',
          required: true,
          helpText: 'Each checklist item should map to a specific audit criterion and clause reference.',
          columns: [
            { id: 'cl_ref',       label: 'Clause Ref',     type: 'text',     required: true, width: 'sm' },
            { id: 'cl_requirement', label: 'Requirement',  type: 'textarea', required: true, width: 'lg' },
            { id: 'cl_evidence',  label: 'Evidence Expected', type: 'text',  required: true, width: 'md' },
            { id: 'cl_auditor',   label: 'Assigned To',    type: 'user_select', required: false, width: 'sm' },
          ],
          minRows: 3,
        },
        {
          id: 'opening_meeting_date',
          name: 'openingMeetingDate',
          label: 'Opening Meeting Date',
          type: 'date',
          required: true,
          helpText: 'Date of the formal opening meeting with auditees',
          normClause: '8.2.4',
        },
        {
          id: 'opening_meeting_attendees',
          name: 'openingMeetingAttendees',
          label: 'Opening Meeting Attendees',
          type: 'textarea',
          placeholder: 'List attendees and their roles...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Audit Execution & Evidence
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s3',
      order: 3,
      title: '3. Audit Execution & Evidence',
      description: 'Document the evidence gathered during the audit: documents reviewed, interviews conducted, observations made.',
      normClause: 'ISO 13485 8.2.4(a)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'documents_reviewed',
          name: 'documentsReviewed',
          label: 'Documents Reviewed',
          type: 'repeater',
          helpText: 'List all documents, records, and data reviewed during the audit.',
          columns: [
            { id: 'dr_number',  label: 'Document Number', type: 'text',   required: true, width: 'md' },
            { id: 'dr_title',   label: 'Title',           type: 'text',   required: true, width: 'lg' },
            { id: 'dr_version', label: 'Rev.',            type: 'text',   required: true, width: 'sm' },
            { id: 'dr_status',  label: 'Compliance',      type: 'select', required: true, width: 'sm',
              options: ['Compliant', 'Minor Gap', 'Major Gap', 'Not Applicable'] },
          ],
          minRows: 1,
        },
        {
          id: 'interviews_conducted',
          name: 'interviewsConducted',
          label: 'Interviews Conducted',
          type: 'repeater',
          columns: [
            { id: 'iv_person',     label: 'Person Interviewed', type: 'user_select', required: true, width: 'md' },
            { id: 'iv_role',       label: 'Role',               type: 'text',        required: false, width: 'md' },
            { id: 'iv_topic',      label: 'Topics Discussed',   type: 'textarea',    required: true, width: 'lg' },
            { id: 'iv_key_points', label: 'Key Points',         type: 'textarea',    required: false, width: 'lg' },
          ],
        },
        {
          id: 'observations',
          name: 'observations',
          label: 'General Observations',
          type: 'rich_text',
          required: true,
          placeholder: 'Summarize key observations, positive findings, areas of concern, and overall impression...',
          helpText: 'Document both positive observations (best practices) and areas of concern',
          normClause: '8.2.4',
        },
        {
          id: 'audit_evidence_files',
          name: 'auditEvidenceFiles',
          label: 'Attachments — Audit Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx', '.msg'],
          maxFileSizeMB: 50,
          helpText: 'Audit plan, checklists, photos, signed attendance sheets, copies of records...',
        },
        {
          id: 'closing_meeting_date',
          name: 'closingMeetingDate',
          label: 'Closing Meeting Date',
          type: 'date',
          required: true,
          helpText: 'Date of the formal closing meeting with auditees to present findings',
          normClause: '8.2.4',
        },
        {
          id: 'closing_meeting_attendees',
          name: 'closingMeetingAttendees',
          label: 'Closing Meeting Attendees',
          type: 'textarea',
          placeholder: 'List attendees and their roles...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Findings
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s4',
      order: 4,
      title: '4. Audit Findings',
      description: 'Document all findings: nonconformities, observations, and opportunities for improvement. Each finding must be linked to a specific clause.',
      normClause: 'ISO 13485 8.2.4(a) / 8.5.2',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'findings_summary',
          name: 'findingsSummary',
          label: 'Findings Summary',
          type: 'section_header',
        },
        {
          id: 'findings',
          name: 'findings',
          label: 'Detailed Findings',
          type: 'repeater',
          required: true,
          requiredForClosure: true,
          helpText: 'Each finding must reference the specific clause, describe the gap, and classify severity.',
          columns: [
            { id: 'fn_id',         label: 'Finding #',          type: 'text',     required: true, width: 'sm' },
            { id: 'fn_severity',   label: 'Severity',           type: 'select',   required: true, width: 'sm',
              options: ['Critical', 'Major', 'Minor', 'Observation'] },
            { id: 'fn_clause',     label: 'Reference Clause',   type: 'text',     required: true, width: 'md' },
            { id: 'fn_description', label: 'Finding Description', type: 'textarea', required: true, width: 'lg' },
            { id: 'fn_evidence',   label: 'Objective Evidence', type: 'textarea', required: true, width: 'lg' },
            { id: 'fn_car',        label: 'CAR Required?',      type: 'checkbox', required: false, width: 'sm' },
            { id: 'fn_capa_ref',   label: 'CAPA Reference',     type: 'text',     required: false, width: 'md' },
          ],
          minRows: 1,
          normClause: '8.5.2',
        },
        {
          id: 'critical_findings_count',
          name: 'criticalFindingsCount',
          label: 'Critical / Major Findings',
          type: 'calculated',
          calculation: {
            sourceFields: ['findings'],
            formula: 'custom',
            expression: 'Count of findings where severity = Critical or Major',
          },
          helpText: 'Auto-calculated from findings above',
          normClause: '8.2.4',
        },
        {
          id: 'positive_observations',
          name: 'positiveObservations',
          label: 'Positive Observations / Best Practices',
          type: 'textarea',
          placeholder: 'Document positive findings, best practices observed, and areas of excellence...',
          helpText: 'Important for balanced audit reporting and recognition of good practices',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Corrective Actions & Management Response
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s5',
      order: 5,
      title: '5. Corrective Actions & Management Response',
      description: 'Define corrective actions for each finding requiring a CAR. Document management response and commitment.',
      normClause: 'ISO 13485 8.5.2(c) / 8.5.3(b)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'management_response',
          name: 'managementResponse',
          label: 'Management Response',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 30 },
          helpText: 'Formal response from the audited area management acknowledging findings and committing to corrective actions.',
          normClause: '5.1 / 8.5.2',
          placeholder: 'Management acknowledges the findings and commits to the following corrective actions...\n\nTimeline for response: within [X] business days\nResources allocated: ...\nAccountability: ...',
        },
        {
          id: 'corrective_action_plan',
          name: 'correctiveActionPlan',
          label: 'Corrective Action Plan',
          type: 'repeater',
          required: true,
          helpText: 'Each action must be SMART and linked to a specific finding number.',
          normClause: '8.5.2(c)',
          columns: [
            { id: 'cap_finding',       label: 'Finding #',       type: 'text',        required: true, width: 'sm' },
            { id: 'cap_action',        label: 'Action',          type: 'textarea',    required: true, width: 'lg' },
            { id: 'cap_responsible',   label: 'Responsible',     type: 'user_select', required: true, width: 'md' },
            { id: 'cap_due_date',      label: 'Due Date',        type: 'date',        required: true, width: 'sm' },
            { id: 'cap_evidence',      label: 'Required Evidence', type: 'text',      required: true, width: 'md' },
            { id: 'cap_status',        label: 'Status',          type: 'select',      required: false, width: 'sm',
              options: ['To Do', 'In Progress', 'Completed', 'Overdue'] },
          ],
          minRows: 1,
        },
        {
          id: 'document_updates_required',
          name: 'documentUpdatesRequired',
          label: 'Document Updates Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'SOPs, WIs, forms, specifications to revise as a result of audit findings',
          normClause: '4.2.3',
        },
        {
          id: 'documents_to_update',
          name: 'documentsToUpdate',
          label: 'Documents to Update',
          type: 'repeater',
          showIf: { fieldId: 'document_updates_required', operator: 'equals', value: 'Yes' },
          columns: [
            { id: 'du_number',  label: 'Document Number',    type: 'text',     required: true, width: 'md' },
            { id: 'du_title',   label: 'Title',              type: 'text',     required: true, width: 'lg' },
            { id: 'du_change',  label: 'Required Change',    type: 'textarea', required: true, width: 'lg' },
            { id: 'du_cc_ref',  label: 'Change Control Ref', type: 'text',     required: false, width: 'md' },
          ],
        },
        {
          id: 'training_required',
          name: 'trainingRequired',
          label: 'Training / Awareness Required?',
          type: 'yes_no_na',
          required: true,
          normClause: '6.2',
        },
        {
          id: 'training_scope',
          name: 'trainingScope',
          label: 'Training Scope',
          type: 'textarea',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Target personnel, training content, planned date...',
        },
        {
          id: 'follow_up_date',
          name: 'followUpDate',
          label: 'Follow-Up Verification Date',
          type: 'date',
          required: true,
          helpText: 'Date by which corrective actions must be verified for effectiveness',
          normClause: '8.5.2(e)',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Executive Summary & Closure
    // ══════════════════════════════════════════════════════════════
    {
      id: 'aud-s6',
      order: 6,
      title: '6. Executive Summary & Closure',
      description: 'Provide an executive summary of the audit results and formally close the audit with QA approval.',
      normClause: 'ISO 13485 8.2.4 / 5.6',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'executive_summary',
          name: 'executiveSummary',
          label: 'Executive Summary',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 100 },
          helpText: 'Comprehensive summary for management review. Include: scope coverage, key findings, risk areas, overall assessment.',
          normClause: '5.6 / 8.2.4',
          placeholder: 'Overall assessment:\n\nScope coverage: [X]% of planned areas audited\n\nKey findings: [summary of critical/major findings]\n\nRisk areas: [areas requiring immediate attention]\n\nPositive observations: [areas of compliance and best practices]\n\nRecommendation: [overall assessment and next steps]',
        },
        {
          id: 'overall_compliance_rating',
          name: 'overallComplianceRating',
          label: 'Overall Compliance Rating',
          type: 'rating',
          required: true,
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: [
            'Non-compliant — Immediate action required',
            'Significant gaps — Major improvements needed',
            'Partially compliant — Some improvements needed',
            'Substantially compliant — Minor improvements needed',
            'Fully compliant — Best practice level',
          ],
          helpText: 'Overall compliance rating based on the evidence gathered and findings identified',
          normClause: '8.2.4',
        },
        {
          id: 'risk_assessment',
          name: 'riskAssessment',
          label: 'Risk Assessment Summary',
          type: 'textarea',
          placeholder: 'Summarize the quality risk level based on findings and their potential impact on product quality, patient safety, and regulatory compliance...',
          normClause: 'ISO 14971 / 7.1',
        },
        {
          id: 'management_review_required',
          name: 'managementReviewRequired',
          label: 'Management Review Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Critical and major findings typically require escalation to management review',
          normClause: '5.6',
        },
        {
          id: 'next_audit_date',
          name: 'nextAuditDate',
          label: 'Recommended Next Audit Date',
          type: 'date',
          helpText: 'Based on findings severity and risk assessment, recommend the next audit frequency',
          normClause: '8.2.4',
        },
        {
          id: 'audit_report_attachments',
          name: 'auditReportAttachments',
          label: 'Attachments — Audit Report',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx'],
          maxFileSizeMB: 50,
          helpText: 'Final audit report, attendance sheets, evidence summary, photos...',
        },
        {
          id: 'qa_approval_signature',
          name: 'qaApprovalSignature',
          label: 'QA Approval Signature — Audit Closure',
          type: 'signature',
          required: true,
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Confirms audit was conducted per procedure and findings are accurately reported.',
          normClause: '21 CFR 11.200 / 8.2.4',
          readOnly: false,
        },
        {
          id: 'closure_date',
          name: 'closureDate',
          label: 'Effective Closure Date',
          type: 'date',
          required: true,
          requiredForClosure: true,
          readOnly: true,
          helpText: 'Auto-filled upon QA signature',
        },
      ],
    },
  ],
};
