/**
 * capa-form-template.ts
 * ─────────────────────
 * Template CAPA complet conforme ISO 13485 8.5.2 / 8.5.3
 *
 * 6 sections - 47 champs - logique conditionnelle - champs calcules
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const CAPA_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-capa-001',
  documentId: 'doc-tmr-capa-001',   // Document Control approuve TMR-CAPA-001
  title: 'CAPA Registration — Corrective and Preventive Action',
  version: '2.0',
  isActive: true,
  recordTarget: 'CAPA',
  normReference: 'ISO 13485:2016 8.5.2 / 8.5.3 / FDA 21 CFR 820.100',
  retentionYears: 5,
  closureRequiredFields: [
    'root_cause_statement',
    'corrective_actions',
    'effectiveness_method',
    'effectiveness_criteria',
    'effectiveness_result',
    'effectiveness_conclusion',
    'qa_approval_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Problem Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Problem Identification',
      description: 'Clearly describe the observed problem, its source and potential impact.',
      normClause: 'ISO 13485 8.5.2(a)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'capa_number',
          name: 'capaNumber',
          label: 'CAPA Number',
          type: 'text',
          readOnly: true,
          helpText: 'Generated automatically',
          normClause: '4.2.4',
        },
        {
          id: 'initiation_date',
          name: 'initiationDate',
          label: 'Initiation Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
        {
          id: 'capa_type',
          name: 'capaType',
          label: 'Action Type',
          type: 'select',
          required: true,
          options: ['Corrective', 'Preventive', 'Continuous Improvement'],
          normClause: '8.5.2 / 8.5.3',
        },
        {
          id: 'source',
          name: 'source',
          label: 'CAPA Source',
          type: 'select',
          required: true,
          options: [
            'Internal Audit',
            'Regulatory Audit / FDA/ANSM Inspection',
            'Customer Complaint',
            'Non-Conformance (NCR)',
            'OOS / OOT Result',
            'Process Deviation',
            'Management Review',
            'Trend Analysis',
            'Risk Assessment (ISO 14971)',
            'Field Return / Recall',
            'Supplier Report',
            'Other',
          ],
          normClause: '8.5.2(a)',
        },
        {
          id: 'source_reference',
          name: 'sourceReference',
          label: 'Source Document Reference',
          type: 'text',
          required: false,
          placeholder: 'e.g. NCR-2024-001, AUD-2024-003, Complaint #12345',
          helpText: 'Number of the record that triggered this CAPA',
        },
        {
          id: 'problem_title',
          name: 'problemTitle',
          label: 'Problem Summary Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'Short factual description (max. 200 characters)',
        },
        {
          id: 'problem_statement',
          name: 'problemStatement',
          label: 'Detailed Problem Statement (5W2H)',
          type: 'rich_text',
          required: true,
          requiredForClosure: false,
          helpText: 'Describe: What, Who, When, Where, Why, How, How many. Be factual — no assumptions at this stage.',
          validation: { minLength: 100 },
          normClause: '8.5.2(a)',
          placeholder: 'WHAT: Describe the observed defect...\nWHO: Who discovered / who is impacted...\nWHEN: Date / frequency...\nWHERE: Location (site, equipment, process step)...\nHOW MANY: Extent, affected lots, quantity...',
        },
        {
          id: 'product_process_affected',
          name: 'productProcessAffected',
          label: 'Affected Product(s) / Process(es)',
          type: 'text',
          required: true,
          placeholder: 'e.g. Product X-200, filling line B, SOP-PROD-001',
        },
        {
          id: 'lots_affected',
          name: 'lotsAffected',
          label: 'Affected Lots',
          type: 'text',
          placeholder: 'e.g. BN-2024-038, BN-2024-039 or N/A',
        },
        {
          id: 'regulatory_impact',
          name: 'regulatoryImpact',
          label: 'Potential Regulatory Impact?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Assess whether this problem may require a regulatory notification (FSCA, Field Safety Notice, MDR...)',
          normClause: '8.2.3',
        },
        {
          id: 'regulatory_impact_justification',
          name: 'regulatoryImpactJustification',
          label: 'Regulatory Impact Justification',
          type: 'textarea',
          showIf: { fieldId: 'regulatory_impact', operator: 'equals', value: 'Yes' },
          required: false,
          placeholder: 'Describe the nature of the impact and potential regulatory actions...',
        },
        {
          id: 'priority',
          name: 'priority',
          label: 'Priority',
          type: 'select',
          required: true,
          options: ['Critical', 'High', 'Medium', 'Low'],
          helpText: 'Critical = direct patient/product impact - High = significant quality risk',
        },
        {
          id: 'initiated_by',
          name: 'initiatedBy',
          label: 'Initiated By',
          type: 'user_select',
          required: true,
          readOnly: true,
          helpText: 'Auto-filled from your session',
        },
        {
          id: 'assigned_to',
          name: 'assignedTo',
          label: 'CAPA Owner',
          type: 'user_select',
          required: true,
          normClause: '8.5.2(b)',
        },
        {
          id: 'target_closure_date',
          name: 'targetClosureDate',
          label: 'Target Closure Date',
          type: 'date',
          required: true,
          normClause: '8.5.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Immediate Containment
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Immediate Containment Action',
      description: 'Actions taken immediately to stop the impact while awaiting the definitive correction.',
      normClause: 'ISO 13485 8.3 / GMP',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'containment_required',
          name: 'containmentRequired',
          label: 'Containment Action Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Quarantine, recall, process stop, etc.',
        },
        {
          id: 'containment_actions',
          name: 'containmentActions',
          label: 'Containment Actions Taken',
          type: 'repeater',
          showIf: { fieldId: 'containment_required', operator: 'equals', value: 'Yes' },
          columns: [
            { id: 'ca_action',      label: 'Action',              type: 'textarea',    required: true, width: 'lg' },
            { id: 'ca_responsible', label: 'Responsible',         type: 'user_select', required: true, width: 'md' },
            { id: 'ca_date',        label: 'Completion Date',     type: 'date',        required: true, width: 'sm' },
            { id: 'ca_done',        label: 'Completed',           type: 'checkbox',    required: false, width: 'sm' },
          ],
          minRows: 1,
          helpText: 'List each immediate action with its owner and completion date',
        },
        {
          id: 'containment_effectiveness',
          name: 'containmentEffectiveness',
          label: 'Containment Effectiveness',
          type: 'select',
          showIf: { fieldId: 'containment_required', operator: 'equals', value: 'Yes' },
          options: ['Effective — problem stopped', 'Partially effective', 'Not effective — escalation required'],
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Root Cause Analysis
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Root Cause Analysis (RCA)',
      description: 'Identify the fundamental cause(s) of the problem. Do not stop at symptoms.',
      normClause: 'ISO 13485 8.5.2(b)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'rca_method',
          name: 'rcaMethod',
          label: 'Analysis Method Used',
          type: 'multi_select',
          required: true,
          options: [
            '5 Whys',
            'Ishikawa Diagram (6M)',
            'Fault Tree Analysis (FTA)',
            'FMEA',
            'Laboratory Investigation',
            'Data / Trend Analysis',
            'Document Review',
            'Interviews / Field Observations',
            'Other',
          ],
          normClause: '8.5.2(b)',
        },

        // ── 5 Whys ──────────────────────────────────────────
        {
          id: 'five_whys',
          name: 'fiveWhys',
          label: '5 Whys Analysis',
          type: 'repeater',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: '5 Whys' },
          helpText: 'Start from the symptom (Why 1) and dig down to the root cause. Minimum 3 levels.',
          columns: [
            { id: 'why_num',    label: 'Level',      type: 'text',     required: true, width: 'sm' },
            { id: 'why_q',      label: 'Why?',       type: 'textarea', required: true, width: 'lg' },
            { id: 'why_a',      label: 'Answer',     type: 'textarea', required: true, width: 'lg' },
          ],
          minRows: 3,
          maxRows: 7,
        },

        // ── Ishikawa 6M ──────────────────────────────────────
        {
          id: 'ishikawa_header',
          name: 'ishikawaHeader',
          label: 'Ishikawa Diagram — 6M Category Analysis',
          type: 'section_header',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
        },
        {
          id: 'ishikawa_man',
          name: 'ishikawaMan',
          label: 'Manpower (Man)',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Missing skills? Insufficient training? Human error? Turnover?',
          normClause: '6.2',
        },
        {
          id: 'ishikawa_machine',
          name: 'ishikawaMachine',
          label: 'Machines / Equipment',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Calibration? Preventive maintenance? Obsolescence? Qualification?',
          normClause: '7.5.1',
        },
        {
          id: 'ishikawa_method',
          name: 'ishikawaMethod',
          label: 'Methods / Procedures',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Missing, obsolete or inadequate procedure? Unclear instructions?',
          normClause: '4.2.3',
        },
        {
          id: 'ishikawa_material',
          name: 'ishikawaMaterial',
          label: 'Materials / Raw Materials',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Raw material non-conformance? Supplier? Storage conditions?',
          normClause: '7.4',
        },
        {
          id: 'ishikawa_measurement',
          name: 'ishikawaMeasurement',
          label: 'Measurement / Controls',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Inadequate analytical method? Uncalibrated instrument? Wrong specification?',
          normClause: '7.6',
        },
        {
          id: 'ishikawa_environment',
          name: 'ishikawaEnvironment',
          label: 'Environment',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Temperature, humidity, cleanliness class, cross-contamination?',
          normClause: '7.5.1',
        },
        {
          id: 'ishikawa_management',
          name: 'ishikawaManagement',
          label: 'Management / Organization',
          type: 'textarea',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: 'Ishikawa Diagram (6M)' },
          placeholder: 'Insufficient resources? Communication? Unclear responsibilities?',
          normClause: '5',
        },

        // ── Root Cause ─────────────────────────────────────────
        {
          id: 'root_cause_statement',
          name: 'rootCauseStatement',
          label: 'Root Cause Statement',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 50 },
          helpText: 'State in one precise and verifiable sentence. The root cause must explain why the problem occurred AND why it was not detected.',
          normClause: '8.5.2(b)',
          placeholder: 'The root cause is: [main causal factor] because [factual explanation]. This problem was not detected because [failed detection mechanism].',
        },
        {
          id: 'systemic_assessment',
          name: 'systemicAssessment',
          label: 'Systemic Extent Assessment',
          type: 'yes_no_na',
          required: true,
          helpText: 'Does this problem exist in other processes, products or sites?',
          normClause: '8.5.2(c)',
        },
        {
          id: 'systemic_scope',
          name: 'systemicScope',
          label: 'Identified Extent',
          type: 'textarea',
          showIf: { fieldId: 'systemic_assessment', operator: 'equals', value: 'Yes' },
          placeholder: 'List other potentially impacted processes / products / sites...',
        },
        {
          id: 'rca_evidence',
          name: 'rcaEvidence',
          label: 'Attachments — Investigation Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx'],
          maxFileSizeMB: 20,
          helpText: 'Analytical data, photos, chromatograms, screenshots, investigation report...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Corrective / Preventive Action Plan
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Action Plan',
      description: 'Define actions that eliminate the root cause (corrective) or prevent occurrence (preventive).',
      normClause: 'ISO 13485 8.5.2(c) / 8.5.3(b)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'corrective_actions',
          name: 'correctiveActions',
          label: 'Detailed Action Plan',
          type: 'repeater',
          required: true,
          requiredForClosure: true,
          normClause: '8.5.2(c)',
          helpText: 'Each action must be SMART: Specific, Measurable, Achievable, Realistic, Time-bound.',
          columns: [
            { id: 'act_num',         label: '#',                   type: 'text',        required: true,  width: 'sm' },
            { id: 'act_description', label: 'Action Description',  type: 'textarea',required: true,  width: 'lg' },
            { id: 'act_type',        label: 'Type',                type: 'select',      required: true,  width: 'sm',
              options: ['Corrective', 'Preventive', 'Detective', 'Systemic'] },
            { id: 'act_responsible', label: 'Responsible',         type: 'user_select', required: true,  width: 'md' },
            { id: 'act_due_date',    label: 'Due Date',            type: 'date',        required: true,  width: 'sm' },
            { id: 'act_evidence',    label: 'Required Evidence',   type: 'text',        required: true,  width: 'md' },
            { id: 'act_status',      label: 'Status',              type: 'select',      required: false, width: 'sm',
              options: ['To Do', 'In Progress', 'Completed', 'Overdue'] },
          ],
          minRows: 1,
        },
        {
          id: 'document_updates_required',
          name: 'documentUpdatesRequired',
          label: 'Document Updates Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'SOPs, WIs, forms, specifications to revise as a result of this CAPA',
          normClause: '4.2.3',
        },
        {
          id: 'documents_to_update',
          name: 'documentsToUpdate',
          label: 'Documents to Update',
          type: 'repeater',
          showIf: { fieldId: 'document_updates_required', operator: 'equals', value: 'Yes' },
          columns: [
            { id: 'doc_number',   label: 'Document Number',    type: 'text',   required: true, width: 'md' },
            { id: 'doc_title',    label: 'Title',              type: 'text',   required: true, width: 'lg' },
            { id: 'doc_change',   label: 'Required Change',    type: 'textarea', required: true, width: 'lg' },
            { id: 'doc_cc_ref',   label: 'Change Control Ref', type: 'text',  required: false, width: 'md' },
          ],
        },
        {
          id: 'training_required',
          name: 'trainingRequired',
          label: 'Training / Awareness Required?',
          type: 'yes_no_na',
          required: true,
          normClause: '6.2',
        },
        {
          id: 'training_scope',
          name: 'trainingScope',
          label: 'Training Scope',
          type: 'textarea',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Target personnel, training content, planned date...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Implementation & Evidence
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Implementation — Objective Evidence',
      description: 'Document evidence of completion for each corrective action.',
      normClause: 'ISO 13485 8.5.2(d)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'implementation_evidence',
          name: 'implementationEvidence',
          label: 'Implementation Evidence per Action',
          type: 'repeater',
          normClause: '8.5.2(d)',
          helpText: 'For each action in the plan (section 4), attach proof of completion.',
          columns: [
            { id: 'ev_action_ref',   label: 'Action #',          type: 'text',    required: true,  width: 'sm' },
            { id: 'ev_description',  label: 'Evidence Provided',  type: 'textarea',required: true,  width: 'lg' },
            { id: 'ev_date',         label: 'Date',              type: 'date',    required: true,  width: 'sm' },
            { id: 'ev_verified_by',  label: 'Verified By',       type: 'user_select', required: true, width: 'md' },
          ],
        },
        {
          id: 'implementation_attachments',
          name: 'implementationAttachments',
          label: 'Attachments — Implementation Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx', '.msg'],
          maxFileSizeMB: 50,
          helpText: 'Revised documents, signed training records, analytical results, before/after photos...',
        },
        {
          id: 'implementation_completion_date',
          name: 'implementationCompletionDate',
          label: 'Implementation Completion Date',
          type: 'date',
          required: true,
          requiredForClosure: true,
          normClause: '8.5.2(d)',
        },
        {
          id: 'qa_review_implementation',
          name: 'qaReviewImplementation',
          label: 'QA Review of Implementation',
          type: 'user_select',
          required: true,
          requiredForClosure: true,
          helpText: 'QA responsible for verifying action implementation',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Effectiveness Verification & Closure
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Effectiveness Verification & Closure',
      description: 'Confirm that corrective actions have eliminated the root cause and the problem does not recur.',
      normClause: 'ISO 13485 8.5.2(e)(f)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'effectiveness_method',
          name: 'effectivenessMethod',
          label: 'Effectiveness Verification Method',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: [
            'Process KPI Monitoring',
            'Post-implementation Data / Trend Analysis',
            'Targeted Follow-up Audit',
            'Inspection / Field Verification',
            'Analytical Results (tests, measurements)',
            'Training Records Review',
            'Batch / Product Re-inspection',
            'Customer Follow-up Survey',
            'Next Management Review',
          ],
          normClause: '8.5.2(e)',
        },
        {
          id: 'effectiveness_criteria',
          name: 'effectivenessCriteria',
          label: 'Acceptance Criteria (measurable)',
          type: 'textarea',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 30 },
          helpText: 'Criteria must be objective and verifiable. Ex: "Zero Grade A environmental excursion over 3 consecutive months" or "100% batch records signed within 48h over 30 lots".',
          normClause: '8.5.2(e)',
          placeholder: 'Criterion 1: [indicator] <=/>= [target value] over [period]\nCriterion 2: ...',
        },
        {
          id: 'effectiveness_period',
          name: 'effectivenessPeriod',
          label: 'Verification Period',
          type: 'date_range',
          required: true,
          helpText: 'Period during which data is collected to verify effectiveness',
        },
        {
          id: 'effectiveness_result',
          name: 'effectivenessResult',
          label: 'Observed Results',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 50 },
          helpText: 'Describe the collected data and compare against defined acceptance criteria.',
          normClause: '8.5.2(f)',
          placeholder: 'Collected data:\nCriterion 1: observed result = ... -> [Conforming / Non-conforming]\nCriterion 2: observed result = ... -> [Conforming / Non-conforming]',
        },
        {
          id: 'effectiveness_conclusion',
          name: 'effectivenessConclusion',
          label: 'Effectiveness Conclusion',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: [
            'Effective — all criteria met',
            'Partially effective — additional actions required',
            'Not effective — CAPA reopening required',
          ],
          normClause: '8.5.2(f)',
        },
        {
          id: 'additional_actions_required',
          name: 'additionalActionsRequired',
          label: 'Additional Actions',
          type: 'textarea',
          showIf: { fieldId: 'effectiveness_conclusion', operator: 'equals', value: 'Partially effective — additional actions required' },
          placeholder: 'Describe additional actions to take and the new target date...',
        },
        {
          id: 'reopen_justification',
          name: 'reopenJustification',
          label: 'Reopening Justification',
          type: 'textarea',
          showIf: { fieldId: 'effectiveness_conclusion', operator: 'equals', value: 'Not effective — CAPA reopening required' },
          required: true,
          placeholder: 'Describe why effectiveness is not achieved and how the new CAPA will address the problem...',
        },
        {
          id: 'lessons_learned',
          name: 'lessonsLearned',
          label: 'Lessons Learned',
          type: 'textarea',
          placeholder: 'Share key learnings to prevent similar problems in other processes...',
          helpText: 'Optional but strongly recommended for continuous improvement (8.5.1)',
          normClause: '8.5.1',
        },
        {
          id: 'effectiveness_attachments',
          name: 'effectivenessAttachments',
          label: 'Attachments — Effectiveness Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png'],
          maxFileSizeMB: 20,
        },

        // ── QA Approval ────────────────────────────────────────
        {
          id: 'qa_approval_signature',
          name: 'qaApprovalSignature',
          label: 'QA Approval Signature — CAPA Closure',
          type: 'signature',
          required: true,
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200 / 8.5.2(f)',
          readOnly: false,
        },
        {
          id: 'closure_date',
          name: 'closureDate',
          label: 'Effective Closure Date',
          type: 'date',
          required: true,
          requiredForClosure: true,
          readOnly: true,
          helpText: 'Auto-filled upon QA signature',
        },
      ],
    },
  ],
};
