/**
 * change-control-form-template.ts
 * ──────────────────────────────────
 * Template Change Control complet conforme ICH Q10 / ISO 13485:2016 §7.3 / FDA 21 CFR 820.70(i)
 *
 * 7 sections - 47 champs - logique conditionnelle - champs calcules
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const CHANGE_CONTROL_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-cc-001',
  documentId: 'doc-tmr-cc-001',   // Document Control approuve TMR-CC-001
  title: 'Change Control Registration — Change Management',
  version: '2.0',
  isActive: true,
  recordTarget: 'ChangeControl',
  normReference: 'ICH Q10 / ISO 13485:2016 §7.3 / FDA 21 CFR 820.70(i)',
  retentionYears: 7,
  closureRequiredFields: [
    'proposed_change',
    'risk_assessment',
    'implementation_plan',
    'implementation_date',
    'qa_approval',
    'approval_signature',
    'implementation_verified',
    'effectiveness_check_date',
    'effectiveness_result',
    'closeout_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Change Request Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Change Request Identification',
      description: 'Identify the change request with unique number, classification, and ownership.',
      normClause: 'ICH Q10',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'cc_number',
          name: 'ccNumber',
          label: 'Change Control Number',
          type: 'text',
          readOnly: true,
          helpText: 'Generated automatically',
          normClause: '4.2.4',
        },
        {
          id: 'initiation_date',
          name: 'initiationDate',
          label: 'Initiation Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
        {
          id: 'title',
          name: 'title',
          label: 'Change Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'Short factual description of the proposed change (max. 200 characters)',
        },
        {
          id: 'type',
          name: 'type',
          label: 'Change Type',
          type: 'select',
          required: true,
          options: ['Planned', 'Unplanned', 'Emergency'],
          helpText: 'Emergency changes require retroactive approval within 72h per FDA 21 CFR 820.70(i)',
          normClause: '820.70(i)',
        },
        {
          id: 'priority',
          name: 'priority',
          label: 'Priority',
          type: 'select',
          required: true,
          options: ['Critical', 'High', 'Medium', 'Low'],
          helpText: 'Critical = direct patient/product impact — High = significant quality risk',
        },
        {
          id: 'category',
          name: 'category',
          label: 'Change Category',
          type: 'select',
          required: true,
          options: [
            'Process',
            'Equipment',
            'Facility',
            'Document',
            'Material',
            'Computer System',
            'Organizational',
          ],
          normClause: '7.3',
        },
        {
          id: 'emergency_justification',
          name: 'emergencyJustification',
          label: 'Emergency Justification',
          type: 'textarea',
          showIf: { fieldId: 'type', operator: 'equals', value: 'Emergency' },
          required: true,
          placeholder: 'Emergency changes require retroactive approval within 72h per FDA 21 CFR 820.70(i)...',
          helpText: 'Document why this change could not follow normal approval flow. Must include risk justification for proceeding without prior approval.',
          normClause: '820.70(i)',
        },
        {
          id: 'initiated_by',
          name: 'initiatedBy',
          label: 'Initiated By',
          type: 'user_select',
          required: true,
          readOnly: true,
          helpText: 'Auto-filled from your session',
        },
        {
          id: 'assigned_to',
          name: 'assignedTo',
          label: 'Change Owner',
          type: 'user_select',
          required: true,
          normClause: '7.3.1',
        },
        {
          id: 'target_completion_date',
          name: 'targetCompletionDate',
          label: 'Target Completion Date',
          type: 'date',
          required: true,
          normClause: '7.3.7',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Description & Justification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Description & Justification',
      description: 'Describe the current situation, justify the need for change, and define the proposed change.',
      normClause: 'ISO 13485 7.3',
      requiredForClosure: true,
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'current_situation',
          name: 'currentSituation',
          label: 'Current Situation',
          type: 'rich_text',
          required: true,
          placeholder: 'Describe the current state that necessitates change...',
          helpText: 'Describe the as-is state, including any non-conformances, inefficiencies, or compliance gaps.',
          normClause: '7.3.2',
        },
        {
          id: 'justification',
          name: 'justification',
          label: 'Justification for Change',
          type: 'textarea',
          required: true,
          placeholder: 'Why is this change needed? Business or compliance justification...',
          helpText: 'Provide business, quality, or regulatory justification for the change.',
          normClause: '7.3.2',
        },
        {
          id: 'regulatory_trigger',
          name: 'regulatoryTrigger',
          label: 'Regulatory Trigger',
          type: 'text',
          placeholder: 'e.g., FDA guidance update, ISO revision, audit finding...',
          helpText: 'Identify any regulatory event that prompted this change request.',
        },
        {
          id: 'proposed_change',
          name: 'proposedChange',
          label: 'Proposed Change',
          type: 'textarea',
          required: true,
          placeholder: 'Describe the proposed change in detail...',
          helpText: 'Describe the to-be state. What will be different after the change is implemented?',
          normClause: '7.3.3',
        },
        {
          id: 'change_scope',
          name: 'changeScope',
          label: 'Change Scope',
          type: 'multi_select',
          required: true,
          options: [
            'Process',
            'Equipment',
            'Facility',
            'Documentation',
            'Material',
            'IT/Software',
            'Personnel',
            'Regulatory',
          ],
          normClause: '7.3.2',
        },
        {
          id: 'affected_products',
          name: 'affectedProducts',
          label: 'Affected Products / Processes / Systems',
          type: 'text',
          placeholder: 'List affected products, processes, or systems...',
          helpText: 'Identify all products, processes, or systems that will be impacted by this change.',
          normClause: '7.3.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Risk & Impact Assessment
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Risk & Impact Assessment',
      description: 'Assess the risk level and potential impact of the proposed change on quality, safety, and compliance.',
      normClause: 'ISO 14971 / ICH Q9',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'risk_assessment',
          name: 'riskAssessment',
          label: 'Risk Assessment Narrative',
          type: 'textarea',
          required: true,
          placeholder: 'Assess probability, severity, and detectability of risks...',
          helpText: 'Provide a qualitative assessment of the risks associated with implementing (and not implementing) this change.',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_probability',
          name: 'riskProbability',
          label: 'Risk Probability',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Very Low', 'Low', 'Medium', 'High', 'Very High'],
          helpText: '1 = Very Low — 5 = Very High probability of occurrence',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_severity',
          name: 'riskSeverity',
          label: 'Risk Severity',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Negligible', 'Minor', 'Moderate', 'Major', 'Critical'],
          helpText: '1 = Negligible — 5 = Critical impact on patient safety or product quality',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_detectability',
          name: 'riskDetectability',
          label: 'Risk Detectability',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Almost Certain', 'High', 'Medium', 'Low', 'Very Unlikely'],
          helpText: '1 = Almost Certain to detect — 5 = Very Unlikely to detect before reaching the patient',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_priority_number',
          name: 'riskPriorityNumber',
          label: 'Risk Priority Number (RPN)',
          type: 'calculated',
          calculation: {
            sourceFields: ['risk_probability', 'risk_severity', 'risk_detectability'],
            formula: 'multiply',
          },
          readOnly: true,
          helpText: 'RPN = Probability × Severity × Detectability. Auto-calculated. Values >100 typically require mitigation.',
          normClause: 'ISO 14971',
        },
        {
          id: 'impact_analysis',
          name: 'impactAnalysis',
          label: 'Impact Analysis',
          type: 'textarea',
          placeholder: 'Analyze potential impact on products, processes, systems...',
          helpText: 'Describe the potential positive and negative impacts of the proposed change.',
          normClause: '7.3.5',
        },
        {
          id: 'impact_validated_systems',
          name: 'impactValidatedSystems',
          label: 'Impact on Validated Systems?',
          type: 'yes_no_na',
          helpText: 'Does this change impact validated systems?',
          normClause: '7.5.6',
        },
        {
          id: 'validated_systems_details',
          name: 'validatedSystemsDetails',
          label: 'Validated Systems — Re-validation Requirements',
          type: 'textarea',
          showIf: { fieldId: 'impact_validated_systems', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe re-validation requirements...',
          helpText: 'Detail the systems impacted and the re-validation activities required.',
          normClause: '7.5.6',
        },
        {
          id: 'impact_regulatory_filing',
          name: 'impactRegulatoryFiling',
          label: 'Impact on Regulatory Filing?',
          type: 'yes_no_na',
          helpText: 'Does this change require an update to any regulatory submission or filing?',
          normClause: '7.3.6',
        },
        {
          id: 'regulatory_filing_details',
          name: 'regulatoryFilingDetails',
          label: 'Regulatory Filing Details',
          type: 'textarea',
          showIf: { fieldId: 'impact_regulatory_filing', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe regulatory filing updates required (e.g., PMA supplement, 510(k), CE technical file update)...',
          helpText: 'Identify the specific regulatory submissions that must be updated.',
          normClause: '7.3.6',
        },
        {
          id: 'impact_product_quality',
          name: 'impactProductQuality',
          label: 'Impact on Product Quality?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Does this change have a potential impact on product quality attributes?',
          normClause: '7.3.5',
        },
        {
          id: 'impact_patient_safety',
          name: 'impactPatientSafety',
          label: 'Impact on Patient Safety?',
          type: 'yes_no_na',
          required: true,
          normClause: 'ISO 14971',
          helpText: 'Does this change have a potential impact on patient safety? If Yes, a full risk analysis per ISO 14971 is required.',
        },
        {
          id: 'affected_areas',
          name: 'affectedAreas',
          label: 'Affected Functional Areas',
          type: 'multi_select',
          options: [
            'Manufacturing',
            'QC',
            'QA',
            'Regulatory',
            'Supply Chain',
            'Warehouse',
            'Engineering',
            'R&D',
            'Other',
          ],
          helpText: 'Select all functional areas that will be impacted by this change.',
          normClause: '7.3.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Implementation Plan
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Implementation Plan',
      description: 'Define the steps, timeline, and resources needed to implement the approved change.',
      normClause: 'ISO 13485 7.3.7',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'implementation_plan',
          name: 'implementationPlan',
          label: 'Implementation Plan Overview',
          type: 'textarea',
          required: true,
          placeholder: 'Outline steps for implementing this change...',
          helpText: 'Provide a high-level overview of the implementation approach.',
          normClause: '7.3.7',
        },
        {
          id: 'implementation_steps',
          name: 'implementationSteps',
          label: 'Implementation Steps',
          type: 'repeater',
          required: true,
          normClause: '7.3.7',
          helpText: 'Break down the implementation into discrete, trackable steps with clear ownership and deadlines.',
          columns: [
            { id: 'step_num',         label: '#',                   type: 'text',        required: true,  width: 'sm' },
            { id: 'step_desc',        label: 'Step Description',    type: 'textarea',    required: true,  width: 'lg' },
            { id: 'step_responsible', label: 'Responsible',         type: 'user_select', required: true,  width: 'md' },
            { id: 'step_due',         label: 'Due Date',            type: 'date',        required: true,  width: 'sm' },
            { id: 'step_status',      label: 'Status',              type: 'select',      required: false, width: 'sm',
              options: ['To Do', 'In Progress', 'Completed'] },
          ],
          minRows: 1,
        },
        {
          id: 'implementation_date',
          name: 'implementationDate',
          label: 'Planned Implementation Date',
          type: 'date',
          required: true,
          normClause: '7.3.7',
        },
        {
          id: 'estimated_cost',
          name: 'estimatedCost',
          label: 'Estimated Cost / Resources',
          type: 'text',
          placeholder: 'e.g., $50,000 or 2 weeks downtime',
          helpText: 'Provide an estimate of the financial or resource impact of implementing this change.',
        },
        {
          id: 'rollback_plan',
          name: 'rollbackPlan',
          label: 'Rollback Plan',
          type: 'textarea',
          helpText: 'What is the rollback plan if the change fails?',
          placeholder: 'Describe the steps to revert to the previous state if the change is unsuccessful...',
          normClause: '7.3.7',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Document & Training Updates
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Document & Training Updates',
      description: 'Identify documents requiring revision and training needs arising from the change.',
      normClause: 'ISO 13485 4.2.3 / 6.2',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'document_updates_required',
          name: 'documentUpdatesRequired',
          label: 'Document Updates Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Are any controlled documents (SOPs, WIs, forms, specifications) impacted by this change?',
          normClause: '4.2.3',
        },
        {
          id: 'documents_to_update',
          name: 'documentsToUpdate',
          label: 'Documents to Update',
          type: 'repeater',
          showIf: { fieldId: 'document_updates_required', operator: 'equals', value: 'Yes' },
          columns: [
            { id: 'doc_number', label: 'Document Number', type: 'text',     required: true, width: 'md' },
            { id: 'doc_title',  label: 'Title',           type: 'text',     required: true, width: 'lg' },
            { id: 'doc_change', label: 'Required Change',  type: 'textarea', required: true, width: 'lg' },
          ],
          helpText: 'List each controlled document that must be revised as part of this change.',
          normClause: '4.2.3',
        },
        {
          id: 'training_required',
          name: 'trainingRequired',
          label: 'Training Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Is training or awareness activity required as a result of this change?',
          normClause: '6.2',
        },
        {
          id: 'training_scope',
          name: 'trainingScope',
          label: 'Training Scope',
          type: 'textarea',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Target personnel, training content, planned date...',
          helpText: 'Describe who needs to be trained, on what content, and by when.',
          normClause: '6.2',
        },
        {
          id: 'communication_required',
          name: 'communicationRequired',
          label: 'Communication Required?',
          type: 'yes_no_na',
          helpText: 'Is formal communication to stakeholders (internal or external) needed for this change?',
        },
        {
          id: 'communication_plan',
          name: 'communicationPlan',
          label: 'Communication Plan',
          type: 'textarea',
          showIf: { fieldId: 'communication_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe the communication plan: audience, channel, content, timeline...',
          helpText: 'Define how and when stakeholders will be informed about this change.',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Approval Chain
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Approval Chain',
      description: 'Required approvals before implementation. Electronic signatures per 21 CFR Part 11.',
      normClause: 'ISO 13485 7.3.5 / 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'requested_by',
          name: 'requestedBy',
          label: 'Requested By',
          type: 'user_select',
          required: true,
          helpText: 'Person requesting the change',
          normClause: '7.3.5',
        },
        {
          id: 'technical_review_by',
          name: 'technicalReviewBy',
          label: 'Technical Review By',
          type: 'user_select',
          helpText: 'Subject matter expert who reviewed the technical feasibility of the change',
          normClause: '7.3.5',
        },
        {
          id: 'qa_approval',
          name: 'qaApproval',
          label: 'QA Approval',
          type: 'user_select',
          requiredForClosure: true,
          helpText: 'Quality Assurance approval is mandatory before implementation can proceed',
          normClause: '7.3.5',
        },
        {
          id: 'regulatory_approval_required',
          name: 'regulatoryApprovalRequired',
          label: 'Regulatory Approval Required?',
          type: 'yes_no_na',
          helpText: 'Is regulatory affairs approval required for this change?',
        },
        {
          id: 'regulatory_approval_by',
          name: 'regulatoryApprovalBy',
          label: 'Regulatory Approval By',
          type: 'user_select',
          showIf: { fieldId: 'regulatory_approval_required', operator: 'equals', value: 'Yes' },
          helpText: 'Regulatory Affairs representative who approved this change',
          normClause: '7.3.6',
        },
        {
          id: 'management_approval_required',
          name: 'managementApprovalRequired',
          label: 'Management Approval Required?',
          type: 'yes_no_na',
          helpText: 'Is senior management approval required? Typically for high-priority or high-cost changes.',
        },
        {
          id: 'management_approval_by',
          name: 'managementApprovalBy',
          label: 'Management Approval By',
          type: 'user_select',
          showIf: { fieldId: 'management_approval_required', operator: 'equals', value: 'Yes' },
          helpText: 'Senior management representative who approved this change',
          normClause: '5.5.1',
        },
        {
          id: 'approval_signature',
          name: 'approvalSignature',
          label: 'Approval Signature',
          type: 'signature',
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200',
          readOnly: false,
        },
        {
          id: 'approval_date',
          name: 'approvalDate',
          label: 'Approval Date',
          type: 'date',
          readOnly: true,
          requiredForClosure: true,
          helpText: 'Auto-filled upon approval signature',
          normClause: '21 CFR 11.200',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 7 — Post-Implementation Review
    // ══════════════════════════════════════════════════════════════
    {
      id: 's7',
      order: 7,
      title: '7. Post-Implementation Review',
      description: 'Verify implementation, assess effectiveness, and formally close out the change control.',
      normClause: 'ISO 13485 7.3.9',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'implementation_verified',
          name: 'implementationVerified',
          label: 'Implementation Verified?',
          type: 'yes_no_na',
          requiredForClosure: true,
          helpText: 'Has the implementation been verified to confirm the change was executed as approved?',
          normClause: '7.3.9',
        },
        {
          id: 'verification_details',
          name: 'verificationDetails',
          label: 'Verification Details',
          type: 'textarea',
          showIf: { fieldId: 'implementation_verified', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe how implementation was verified, who performed the verification, and when...',
          helpText: 'Provide details of the verification activities performed.',
          normClause: '7.3.9',
        },
        {
          id: 'effectiveness_check_method',
          name: 'effectivenessCheckMethod',
          label: 'Effectiveness Check Method',
          type: 'select',
          options: [
            'Process KPI Monitoring',
            'Follow-up Audit',
            'Product Testing',
            'Inspection',
            'Data Review',
          ],
          helpText: 'Select the method that will be used to verify the effectiveness of this change.',
          normClause: '7.3.9',
        },
        {
          id: 'effectiveness_check_date',
          name: 'effectivenessCheckDate',
          label: 'Effectiveness Check Date',
          type: 'date',
          requiredForClosure: true,
          helpText: 'Date by which effectiveness of the change will be evaluated.',
          normClause: '7.3.9',
        },
        {
          id: 'effectiveness_result',
          name: 'effectivenessResult',
          label: 'Effectiveness Result',
          type: 'textarea',
          requiredForClosure: true,
          placeholder: 'Was the change effective? Compare actual vs expected results...',
          helpText: 'Document the observed results and compare against the expected outcome of the change.',
          normClause: '7.3.9',
        },
        {
          id: 'lessons_learned',
          name: 'lessonsLearned',
          label: 'Lessons Learned',
          type: 'textarea',
          placeholder: 'Key learnings from this change...',
          helpText: 'Optional but recommended — share key learnings to improve future change management activities.',
          normClause: '8.5.1',
        },
        {
          id: 'closeout_signature',
          name: 'closeoutSignature',
          label: 'Closeout Signature',
          type: 'signature',
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Confirms formal closeout of this change control.',
          normClause: '21 CFR 11.200',
          readOnly: false,
        },
        {
          id: 'closeout_date',
          name: 'closeoutDate',
          label: 'Closeout Date',
          type: 'date',
          readOnly: true,
          requiredForClosure: true,
          helpText: 'Auto-filled upon closeout signature',
          normClause: '21 CFR 11.200',
        },
      ],
    },
  ],
};
