/**
 * deviation-form-template.ts
 * ─────────────────────────────
 * Template Deviation complet conforme ISO 13485:2016 §8.7 / cGMP 21 CFR 211.192 / FDA 21 CFR 820.90
 *
 * 6 sections - 47 champs - logique conditionnelle - champs calcules
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const DEVIATION_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-deviation-001',
  documentId: 'doc-tmr-deviation-001',   // Document Control approuve TMR-DEV-001
  title: 'Deviation Registration — Deviation Report',
  version: '1.0',
  isActive: true,
  recordTarget: 'Deviation',
  normReference: 'ISO 13485:2016 §8.7 / cGMP 21 CFR 211.192 / FDA 21 CFR 820.90',
  retentionYears: 5,
  closureRequiredFields: [
    'corrective_action',
    'investigation_summary',
    'root_cause_determined',
    'effectiveness_verification',
    'effectiveness_date',
    'qa_review',
    'closure_signature',
    'disposition_final',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Deviation Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Deviation Identification',
      description: 'Identify the deviation, its classification, severity and responsible personnel.',
      normClause: 'ISO 13485 8.7',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'dev_number',
          name: 'devNumber',
          label: 'Deviation Number',
          type: 'text',
          readOnly: true,
          helpText: 'Auto-generated upon creation',
          normClause: '4.2.4',
        },
        {
          id: 'detection_date',
          name: 'detectionDate',
          label: 'Detection Date',
          type: 'date',
          required: true,
          normClause: '8.7',
        },
        {
          id: 'title',
          name: 'title',
          label: 'Deviation Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'Short factual description of the deviation (min. 10 characters)',
          normClause: '8.7',
        },
        {
          id: 'type',
          name: 'type',
          label: 'Deviation Type',
          type: 'select',
          required: true,
          options: ['Planned', 'Unplanned'],
          helpText: 'Planned = pre-approved temporary departure; Unplanned = unexpected deviation discovered during execution',
          normClause: '8.7',
        },
        {
          id: 'severity',
          name: 'severity',
          label: 'Severity',
          type: 'select',
          required: true,
          options: ['Critical', 'Major', 'Minor'],
          helpText: 'Critical = direct patient safety impact; Major = significant quality/process impact; Minor = limited impact',
          normClause: '8.7',
        },
        {
          id: 'category',
          name: 'category',
          label: 'Category',
          type: 'select',
          required: true,
          options: ['Process', 'Equipment', 'Material', 'Environment', 'Personnel', 'Documentation'],
          normClause: '8.7',
        },
        {
          id: 'planned_deviation_notice',
          name: 'plannedDeviationNotice',
          label: 'Planned Deviation — Additional Requirements',
          type: 'section_header',
          showIf: { fieldId: 'type', operator: 'equals', value: 'Planned' },
        },
        {
          id: 'planned_deviation_warning',
          name: 'plannedDeviationWarning',
          label: 'Planned Deviation Justification',
          type: 'textarea',
          showIf: { fieldId: 'type', operator: 'equals', value: 'Planned' },
          required: true,
          helpText: 'Planned deviations require documented justification per ISO 13485 §8.7',
          placeholder: 'Justify why this planned deviation is necessary and the expected outcome...',
          normClause: '8.7',
        },
        {
          id: 'detected_by',
          name: 'detectedBy',
          label: 'Detected By',
          type: 'user_select',
          required: true,
          helpText: 'Person who identified or reported the deviation',
          normClause: '8.7',
        },
        {
          id: 'assigned_to',
          name: 'assignedTo',
          label: 'Assigned To',
          type: 'user_select',
          required: true,
          helpText: 'Responsible person for managing the deviation investigation',
          normClause: '8.7',
        },
        {
          id: 'target_closure_date',
          name: 'targetClosureDate',
          label: 'Target Closure Date',
          type: 'date',
          required: true,
          normClause: '8.7',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Deviation Details
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Deviation Details',
      description: 'Describe what happened, the expected versus actual result, and the specification not met.',
      normClause: 'ISO 13485 8.7(a)',
      requiredForClosure: true,
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'description',
          name: 'description',
          label: 'Brief Description',
          type: 'textarea',
          required: true,
          placeholder: 'Brief description of the deviation...',
          normClause: '8.7(a)',
        },
        {
          id: 'detailed_description',
          name: 'detailedDescription',
          label: 'Detailed Description (5W2H)',
          type: 'rich_text',
          required: true,
          validation: { minLength: 50 },
          placeholder: 'Detailed description: What happened, When, Where, How it was discovered...',
          helpText: 'Describe: What, Who, When, Where, Why, How, How many. Be factual — no assumptions at this stage.',
          normClause: '8.7(a)',
        },
        {
          id: 'sop_reference',
          name: 'sopReference',
          label: 'SOP / Procedure Reference',
          type: 'text',
          placeholder: 'e.g., SOP-QC-001 v3.2 — the procedure that was deviated from',
          helpText: 'Reference the specific procedure, work instruction or specification that was deviated from',
          normClause: '4.2.3',
        },
        {
          id: 'expected_result',
          name: 'expectedResult',
          label: 'Expected Result',
          type: 'textarea',
          placeholder: 'What should have happened per procedure...',
          normClause: '8.7(a)',
        },
        {
          id: 'actual_result',
          name: 'actualResult',
          label: 'Actual Result',
          type: 'textarea',
          placeholder: 'What actually happened...',
          normClause: '8.7(a)',
        },
        {
          id: 'deviation_from_specification',
          name: 'deviationFromSpecification',
          label: 'Deviation from Specification',
          type: 'textarea',
          placeholder: 'Specify the specification or acceptance criterion that was not met...',
          helpText: 'Identify the exact specification, limit or acceptance criterion that was exceeded or not met',
          normClause: '8.7(a)',
        },
        {
          id: 'deviation_code',
          name: 'deviationCode',
          label: 'Deviation Code',
          type: 'select',
          options: ['GMP Deviation', 'Quality Deviation', 'Safety Deviation', 'Environmental Deviation', 'Regulatory Deviation'],
          helpText: 'Classification code for trending and regulatory reporting',
          normClause: '8.7',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Product & Lot Information
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Product & Lot Information',
      description: 'Identify the affected product, lot(s), quantities and current disposition.',
      normClause: 'ISO 13485 8.7(b)',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'product_code',
          name: 'productCode',
          label: 'Product Code',
          type: 'text',
          placeholder: 'e.g., PROD-001',
          normClause: '8.7(b)',
        },
        {
          id: 'product_name',
          name: 'productName',
          label: 'Product Name',
          type: 'text',
          placeholder: 'Product name',
          normClause: '8.7(b)',
        },
        {
          id: 'lot_number',
          name: 'lotNumber',
          label: 'Lot / Batch Number',
          type: 'text',
          placeholder: 'e.g., BN-2024-001',
          normClause: '8.7(b)',
        },
        {
          id: 'quantity_affected',
          name: 'quantityAffected',
          label: 'Quantity Affected',
          type: 'number',
          validation: { min: 0 },
          placeholder: 'Number of units affected',
          normClause: '8.7(b)',
        },
        {
          id: 'quantity_at_risk',
          name: 'quantityAtRisk',
          label: 'Quantity at Risk',
          type: 'number',
          validation: { min: 0 },
          placeholder: 'Estimated quantity potentially at risk',
          helpText: 'Estimated number of units that may be impacted beyond the directly affected quantity',
          normClause: '8.7(b)',
        },
        {
          id: 'product_stage',
          name: 'productStage',
          label: 'Product Stage',
          type: 'select',
          options: ['Raw Material', 'In-Process', 'Finished Product', 'Stability', 'Other'],
          normClause: '8.7(b)',
        },
        {
          id: 'isolation_status',
          name: 'isolationStatus',
          label: 'Product / Material Isolated?',
          type: 'checkbox',
          helpText: 'Product/material has been physically isolated and quarantined',
          normClause: '8.3',
        },
        {
          id: 'isolation_details',
          name: 'isolationDetails',
          label: 'Isolation Details',
          type: 'textarea',
          showIf: { fieldId: 'isolation_status', operator: 'equals', value: true },
          placeholder: 'Describe isolation location and quarantine measures...',
          normClause: '8.3',
        },
        {
          id: 'disposition_recommendation',
          name: 'dispositionRecommendation',
          label: 'Disposition Recommendation',
          type: 'select',
          options: ['Release', 'Rework', 'Reject', 'Return to Supplier', 'Pending Investigation', 'Other'],
          helpText: 'Initial recommended disposition pending full investigation',
          normClause: '8.7(b)',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Risk & Impact Assessment
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Risk & Impact Assessment',
      description: 'Assess risk using probability, severity and detectability. Evaluate impact on validated state, regulatory filings and patient safety.',
      normClause: 'ISO 14971 / ICH Q9',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'risk_assessment',
          name: 'riskAssessment',
          label: 'Risk Assessment Narrative',
          type: 'textarea',
          required: true,
          placeholder: 'Assess probability, severity, detectability...',
          helpText: 'Provide a qualitative risk assessment considering the deviation context',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_probability',
          name: 'riskProbability',
          label: 'Probability of Occurrence',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Very Low', 'Low', 'Medium', 'High', 'Very High'],
          helpText: 'Likelihood of the deviation causing harm (1 = very unlikely, 5 = almost certain)',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_severity',
          name: 'riskSeverity',
          label: 'Severity of Harm',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Negligible', 'Minor', 'Moderate', 'Major', 'Critical'],
          helpText: 'Potential severity of harm if the deviation is not controlled (1 = negligible, 5 = critical)',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_detectability',
          name: 'riskDetectability',
          label: 'Detectability',
          type: 'rating',
          ratingMin: 1,
          ratingMax: 5,
          ratingLabels: ['Almost Certain Detection', 'High', 'Medium', 'Low', 'Undetectable'],
          helpText: 'Ability to detect the deviation before causing harm (1 = easily detected, 5 = undetectable)',
          normClause: 'ISO 14971',
        },
        {
          id: 'risk_priority_number',
          name: 'riskPriorityNumber',
          label: 'Risk Priority Number (RPN)',
          type: 'calculated',
          calculation: {
            sourceFields: ['risk_probability', 'risk_severity', 'risk_detectability'],
            formula: 'multiply',
          },
          readOnly: true,
          helpText: 'RPN = Probability × Severity × Detectability (auto-calculated)',
          normClause: 'ISO 14971',
        },
        {
          id: 'justification',
          name: 'justification',
          label: 'Planned Deviation Justification',
          type: 'textarea',
          showIf: { fieldId: 'type', operator: 'equals', value: 'Planned' },
          required: true,
          placeholder: 'Required for planned deviations...',
          helpText: 'Document the justification for accepting the risk associated with this planned deviation',
          normClause: '8.7',
        },
        {
          id: 'impact_validated_state',
          name: 'impactValidatedState',
          label: 'Impact on Validated State?',
          type: 'yes_no_na',
          helpText: 'Does this deviation impact the validated state of equipment/process?',
          normClause: '7.5.6',
        },
        {
          id: 'validated_state_details',
          name: 'validatedStateDetails',
          label: 'Validated State Impact Details',
          type: 'textarea',
          showIf: { fieldId: 'impact_validated_state', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe the impact on validated state and whether revalidation is required...',
          normClause: '7.5.6',
        },
        {
          id: 'impact_regulatory_filing',
          name: 'impactRegulatoryFiling',
          label: 'Impact on Regulatory Filing?',
          type: 'yes_no_na',
          helpText: 'Assess whether this deviation may impact a regulatory submission or approved filing',
          normClause: '8.2.3',
        },
        {
          id: 'regulatory_filing_details',
          name: 'regulatoryFilingDetails',
          label: 'Regulatory Filing Impact Details',
          type: 'textarea',
          showIf: { fieldId: 'impact_regulatory_filing', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe the regulatory impact and any required notifications...',
          normClause: '8.2.3',
        },
        {
          id: 'impact_product_quality',
          name: 'impactProductQuality',
          label: 'Impact on Product Quality?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Does this deviation affect the quality, safety or efficacy of the product?',
          normClause: '8.7',
        },
        {
          id: 'impact_patient_safety',
          name: 'impactPatientSafety',
          label: 'Impact on Patient Safety?',
          type: 'yes_no_na',
          required: true,
          normClause: 'ISO 14971',
          helpText: 'Does this deviation pose any risk to patient or user safety?',
        },
        {
          id: 'immediate_containment',
          name: 'immediateContainment',
          label: 'Immediate Containment Actions',
          type: 'textarea',
          required: true,
          placeholder: 'Describe immediate containment actions taken...',
          helpText: 'Actions taken to immediately contain the deviation and prevent further impact',
          normClause: '8.3',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Corrective & Preventive Actions
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Corrective & Preventive Actions',
      description: 'Define actions to correct the deviation and prevent recurrence. Link to CAPA if required.',
      normClause: 'ISO 13485 8.5.2 / 8.5.3',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'corrective_action',
          name: 'correctiveAction',
          label: 'Corrective Action',
          type: 'textarea',
          required: true,
          requiredForClosure: true,
          placeholder: 'Actions to correct the current deviation...',
          normClause: '8.5.2',
        },
        {
          id: 'preventive_action',
          name: 'preventiveAction',
          label: 'Preventive Action',
          type: 'textarea',
          placeholder: 'Actions to prevent recurrence...',
          normClause: '8.5.3',
        },
        {
          id: 'action_plan',
          name: 'actionPlan',
          label: 'Action Plan',
          type: 'repeater',
          required: true,
          normClause: '8.5.2(c)',
          helpText: 'Each action must be SMART: Specific, Measurable, Achievable, Realistic, Time-bound.',
          columns: [
            { id: 'act_num',         label: '#',              type: 'text',        required: true,  width: 'sm' },
            { id: 'act_desc',        label: 'Action',         type: 'textarea',    required: true,  width: 'lg' },
            { id: 'act_type',        label: 'Type',           type: 'select',      required: true,  width: 'sm',
              options: ['Corrective', 'Preventive', 'Containment'] },
            { id: 'act_responsible', label: 'Responsible',    type: 'user_select', required: true,  width: 'md' },
            { id: 'act_due',         label: 'Due Date',       type: 'date',        required: true,  width: 'sm' },
            { id: 'act_status',      label: 'Status',         type: 'select',      required: false, width: 'sm',
              options: ['To Do', 'In Progress', 'Completed', 'Overdue'] },
          ],
          minRows: 1,
        },
        {
          id: 'capa_required',
          name: 'capaRequired',
          label: 'CAPA Required?',
          type: 'yes_no_na',
          required: true,
          normClause: '8.5.2',
          helpText: 'Determine whether a full CAPA investigation is warranted based on the deviation severity and recurrence',
        },
        {
          id: 'linked_capa_id',
          name: 'linkedCapaId',
          label: 'Linked CAPA Reference',
          type: 'text',
          showIf: { fieldId: 'capa_required', operator: 'equals', value: 'Yes' },
          placeholder: 'CAPA reference number',
          helpText: 'Enter the CAPA record number that has been initiated for this deviation',
          normClause: '8.5.2',
        },
        {
          id: 'linked_document_id',
          name: 'linkedDocumentId',
          label: 'Linked Document Reference',
          type: 'text',
          placeholder: 'Linked document reference number',
          helpText: 'Reference to any related change control, investigation or other QMS document',
        },
        {
          id: 'deviation_attachments',
          name: 'deviationAttachments',
          label: 'Attachments — Deviation Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx'],
          maxFileSizeMB: 25,
          helpText: 'Supporting evidence: photos, data, batch records, analytical results, correspondence...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Review & Closure
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Review & Closure',
      description: 'Investigation summary, root cause determination, effectiveness verification and QA closure.',
      normClause: 'ISO 13485 8.7(d) / 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'investigation_summary',
          name: 'investigationSummary',
          label: 'Investigation Summary',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          placeholder: 'Summarize the investigation findings and conclusions...',
          helpText: 'Provide a comprehensive summary of the investigation including methodology, findings and conclusions',
          normClause: '8.7(d)',
        },
        {
          id: 'root_cause_determined',
          name: 'rootCauseDetermined',
          label: 'Root Cause Determined?',
          type: 'yes_no_na',
          required: true,
          requiredForClosure: true,
          helpText: 'Was a root cause identified during the investigation?',
          normClause: '8.5.2(b)',
        },
        {
          id: 'root_cause_statement',
          name: 'rootCauseStatement',
          label: 'Root Cause Statement',
          type: 'textarea',
          showIf: { fieldId: 'root_cause_determined', operator: 'equals', value: 'Yes' },
          requiredForClosure: true,
          placeholder: 'State the root cause...',
          helpText: 'State in one precise and verifiable sentence why the deviation occurred and why it was not detected',
          normClause: '8.5.2(b)',
        },
        {
          id: 'effectiveness_verification',
          name: 'effectivenessVerification',
          label: 'Effectiveness Verification',
          type: 'textarea',
          required: true,
          requiredForClosure: true,
          placeholder: 'How will you verify the corrective action was effective?',
          helpText: 'Describe the method and criteria for verifying that corrective actions have eliminated the deviation cause',
          normClause: '8.5.2(e)',
        },
        {
          id: 'effectiveness_date',
          name: 'effectivenessDate',
          label: 'Effectiveness Verification Date',
          type: 'date',
          required: true,
          requiredForClosure: true,
          helpText: 'Date by which effectiveness will be verified',
          normClause: '8.5.2(e)',
        },
        {
          id: 'qa_review',
          name: 'qaReview',
          label: 'QA Review By',
          type: 'user_select',
          required: true,
          requiredForClosure: true,
          helpText: 'QA responsible for reviewing and closing',
          normClause: '8.7(d)',
        },
        {
          id: 'closure_signature',
          name: 'closureSignature',
          label: 'Closure Signature — QA Approval',
          type: 'signature',
          required: true,
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200',
          readOnly: false,
        },
        {
          id: 'closure_date',
          name: 'closureDate',
          label: 'Closure Date',
          type: 'date',
          readOnly: true,
          requiredForClosure: true,
          helpText: 'Auto-filled upon QA closure signature',
          normClause: '8.7(d)',
        },
        {
          id: 'disposition_final',
          name: 'dispositionFinal',
          label: 'Final Disposition',
          type: 'select',
          requiredForClosure: true,
          options: ['Release', 'Rework', 'Reject', 'Return to Supplier', 'Use As-Is with Justification'],
          helpText: 'Final product/material disposition decision based on investigation conclusions',
          normClause: '8.7(b)',
        },
      ],
    },
  ],
};
