/**
 * document-form-template.ts
 * ────────────────────────────
 * Template Document complet conforme ISO 13485 4.2.3 / 4.2.4
 *
 * Subtilite : le niveau du document (N1-N4) influe sur le template.
 *   - N1 (Policy)      : documents strategiques, gouvernance, referentiel reglementaire
 *   - N2 (SOP)         : procedures operationnelles, gouvernees par N1
 *   - N3 (WI)          : instructions de travail detaillees, gouvernees par N2
 *   - N4 (Form/Record) : formulaires & enregistrements, gouvernes par N3
 *                        N4 genere des enregistrements soumis au workflow de validation
 *
 * 8 sections - 65+ champs - logique conditionnelle par niveau
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const DOCUMENT_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-doc-001',
  documentId: 'doc-tmr-doc-001',   // Document Control approuve TMR-DOC-001
  title: 'Document Registration — Quality Document Management',
  version: '2.0',
  isActive: true,
  recordTarget: 'Documents',
  normReference: 'ISO 13485:2016 4.2.3 / 4.2.4 / FDA 21 CFR 820.40 / 21 CFR Part 11',
  retentionYears: 15,
  closureRequiredFields: [
    'doc_number',
    'doc_title',
    'doc_type',
    'doc_level',
    'doc_classification',
    'doc_scope',
    'doc_owner',
    'review_method',
    'approval_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Document Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Document Identification',
      description: 'Core identification fields common to all document levels. The document level (N1–N4) determines which additional sections appear below.',
      normClause: 'ISO 13485 4.2.3(a)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'doc_number',
          name: 'docNumber',
          label: 'Document Number',
          type: 'text',
          required: true,
          requiredForClosure: true,
          readOnly: true,
          helpText: 'Auto-generated based on document level and type. Format: {TYPE}-QMS-{NNN}',
          normClause: '4.2.3(a)',
          placeholder: 'SOP-QMS-001',
        },
        {
          id: 'doc_title',
          name: 'docTitle',
          label: 'Document Title',
          type: 'text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 5, maxLength: 200 },
          placeholder: 'Descriptive title following naming conventions',
          normClause: '4.2.3(a)',
        },
        {
          id: 'doc_level',
          name: 'docLevel',
          label: 'Document Level (N1–N4)',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: [
            'N1 — Policy / Politique',
            'N2 — SOP / Procedure',
            'N3 — WI / Instruction de travail',
            'N4 — Form/Record / Formulaire-Enregistrement',
          ],
          helpText: 'N1 = strategic governance, N2 = operational procedures, N3 = detailed work instructions, N4 = forms & records. This selection dynamically shows/hides relevant sections below.',
          normClause: '4.2.3',
        },
        {
          id: 'doc_type',
          name: 'docType',
          label: 'Document Type',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: [
            'SOP',
            'WI',
            'Form',
            'Policy',
            'Specification',
            'Technical',
            'Risk Analysis',
            'Validation Protocol',
            'Record',
          ],
          normClause: '4.2.3',
        },
        {
          id: 'doc_version',
          name: 'docVersion',
          label: 'Version',
          type: 'text',
          required: true,
          readOnly: true,
          defaultValue: '1.0',
          helpText: 'Auto-set to 1.0 for new documents. Incremented on revision.',
          normClause: '4.2.3(c)',
        },
        {
          id: 'doc_classification',
          name: 'docClassification',
          label: 'Classification',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: ['Internal', 'External', 'Regulatory', 'Confidential'],
          helpText: 'Internal = internal use only, External = from external sources, Regulatory = from regulatory bodies, Confidential = restricted distribution',
          normClause: '4.2.3',
        },
        {
          id: 'doc_department',
          name: 'docDepartment',
          label: 'Department / Department',
          type: 'select',
          required: true,
          options: [
            'Quality Assurance',
            'Quality Control',
            'Production',
            'Regulatory Affairs',
            'R&D',
            'Engineering',
            'Supply Chain',
            'Pharmacovigilance',
            'Clinical Affairs',
            'IT / Data Integrity',
            'Management',
            'Other',
          ],
          normClause: '4.2.3',
        },
        {
          id: 'doc_owner',
          name: 'docOwner',
          label: 'Document Owner',
          type: 'user_select',
          required: true,
          requiredForClosure: true,
          helpText: 'Person responsible for the content and maintenance of this document',
          normClause: '4.2.3',
        },
        {
          id: 'doc_initiation_date',
          name: 'docInitiationDate',
          label: 'Initiation Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Scope & Description
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Scope & Description / Périmètre & Description',
      description: 'Define the scope, applicability and detailed description of the document. Fields vary by document level.',
      normClause: 'ISO 13485 4.2.3(b)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'doc_description',
          name: 'docDescription',
          label: 'Document Description',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 30 },
          helpText: 'Provide a clear description of the document purpose, scope of application, and intended audience.',
          normClause: '4.2.3(b)',
          placeholder: 'This document defines / describes / establishes...',
        },
        {
          id: 'doc_scope',
          name: 'docScope',
          label: 'Scope / Périmètre d\'application',
          type: 'textarea',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 20 },
          helpText: 'What is covered by this document? What sites, processes, products, or departments are in scope?',
          normClause: '4.2.3(b)',
          placeholder: 'This document applies to [sites/departments/processes/products]...\nScope includes: ...\nScope excludes: ...',
        },

        // ── N1 specific: Strategic Scope ──
        {
          id: 'n1_strategic_objectives',
          name: 'n1StrategicObjectives',
          label: 'Strategic Objectives / Objectifs stratégiques',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          helpText: 'N1: Define the strategic objectives this policy addresses. How does it align with the organization\'s quality policy and business goals?',
          normClause: '5.2 / 5.3',
          placeholder: 'This policy supports the following strategic objectives:\n1. ...\n2. ...',
        },
        {
          id: 'n1_regulatory_framework',
          name: 'n1RegulatoryFramework',
          label: 'Regulatory Framework / Referentiel reglementaire',
          type: 'multi_select',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          options: [
            'ISO 13485:2016',
            'FDA 21 CFR 820',
            'FDA 21 CFR Part 11',
            'EU MDR 2017/745',
            'EU IVDR 2017/746',
            'ISO 14971:2019',
            'ICH Q10',
            'ICH Q9',
            'ANSM Guidelines',
            'WHO GMP',
            'Other',
          ],
          helpText: 'N1: Identify all regulatory frameworks this policy maps to.',
          normClause: '4.2.3',
        },

        // ── N2 specific: Process Scope ──
        {
          id: 'n2_processes_covered',
          name: 'n2ProcessesCovered',
          label: 'Processes Covered / Processus couverts',
          type: 'multi_select',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N2 — SOP / Procedure' },
          required: true,
          options: [
            'Document Control',
            'Record Control',
            'CAPA Management',
            'Non-Conformance Management',
            'Audit Management',
            'Risk Management',
            'Change Control',
            'Supplier Management',
            'Production',
            'Quality Control / Testing',
            'Training & Competence',
            'Complaint Handling',
            'Management Review',
            'Validation & Qualification',
            'Calibration & Maintenance',
            'Distribution & Traceability',
            'Other',
          ],
          helpText: 'N2: Identify which QMS processes this SOP covers.',
          normClause: '4.2.3',
        },
        {
          id: 'n2_rationale',
          name: 'n2Rationale',
          label: 'SOP Rationale / Justification de la procedure',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N2 — SOP / Procedure' },
          required: true,
          helpText: 'N2: Explain why this SOP is needed. What problem does it solve? What risk does it mitigate?',
          placeholder: 'This SOP is required to ensure consistent execution of [process] in compliance with [regulation/standard]...',
        },

        // ── N3 specific: Task Scope ──
        {
          id: 'n3_task_description',
          name: 'n3TaskDescription',
          label: 'Task Description / Description de la tache',
          type: 'rich_text',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N3 — WI / Instruction de travail' },
          required: true,
          validation: { minLength: 50 },
          helpText: 'N3: Describe the specific task(s) this work instruction covers. Step-by-step detail expected.',
          placeholder: 'This work instruction describes the step-by-step procedure for [specific task]...',
        },
        {
          id: 'n3_prerequisites',
          name: 'n3Prerequisites',
          label: 'Prerequisites / Prerequis',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N3 — WI / Instruction de travail' },
          required: true,
          helpText: 'N3: What must be completed or in place before performing this task? Training, material, equipment, environment...',
          placeholder: 'Required training: ...\nRequired materials: ...\nRequired equipment: ...\nEnvironmental conditions: ...',
        },
        {
          id: 'n3_safety_warnings',
          name: 'n3SafetyWarnings',
          label: 'Safety Warnings / Avertissements de securite',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N3 — WI / Instruction de travail' },
          helpText: 'N3: Any safety hazards, PPE requirements, or critical precautions. Leave empty if N/A.',
          placeholder: '⚠ Chemical hazard: wear appropriate PPE (gloves, goggles)\n⚠ Electrical hazard: lockout/tagout required...',
        },

        // ── N4 specific: Record Purpose ──
        {
          id: 'n4_record_purpose',
          name: 'n4RecordPurpose',
          label: 'Record Purpose / Objet de l\'enregistrement',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          helpText: 'N4: What data does this form/record capture? Why is this record required? What decisions does it support?',
          normClause: '4.2.4',
          placeholder: 'This record captures [data type] to demonstrate compliance with [clause/regulation]. It supports [decision/process].',
        },
        {
          id: 'n4_data_integrity',
          name: 'n4DataIntegrity',
          label: 'Data Integrity — ALCOA+ Compliance',
          type: 'multi_select',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          options: [
            'Attributable — who performed the action',
            'Legible — readable and permanent',
            'Contemporaneous — recorded at the time',
            'Original — primary record or certified copy',
            'Accurate — free from errors',
            'Complete — all data including repeat tests',
            'Consistent — chronological, no gaps',
            'Enduring — recorded on appropriate media',
            'Available — accessible for review/audit',
          ],
          helpText: 'N4: ALCOA+ principles that this record must comply with. Select all that apply.',
          normClause: '21 CFR Part 11 / 4.2.4',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Hierarchy & Relationships
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Document Hierarchy & Relationships / Hierarchie & Liens',
      description: 'Define where this document sits in the hierarchy. N1 has no parent; N2–N4 must reference their parent document.',
      normClause: 'ISO 13485 4.2.3',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        // ── Parent Document: N/A for N1, required for N2-N4 ──
        {
          id: 'parent_doc_reference',
          name: 'parentDocReference',
          label: 'Parent Document Reference',
          type: 'text',
          showIf: { fieldId: 'doc_level', operator: 'not_equals', value: 'N1 — Policy / Politique' },
          required: true,
          helpText: 'N2-N4: Reference the governing parent document. N2→N1, N3→N2, N4→N3. This is critical for hierarchy integrity.',
          normClause: '4.2.3',
          placeholder: 'e.g. POL-QMS-001 (parent policy), SOP-PROD-010 (parent SOP)',
        },
        {
          id: 'n1_hierarchy_note',
          name: 'n1HierarchyNote',
          label: 'N1 — Top-Level Document',
          type: 'section_header',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
        },
        {
          id: 'n1_no_parent_info',
          name: 'n1NoParentInfo',
          label: 'N1 policies are top-level documents and do not require a parent document. They govern N2 SOPs.',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          readOnly: true,
          defaultValue: 'This is a top-level (N1) document. No parent document required.',
        },

        // ── Child Documents ──
        {
          id: 'child_documents',
          name: 'childDocuments',
          label: 'Child Documents / Documents enfants (known)',
          type: 'repeater',
          helpText: 'List known child documents governed by this document. N1→N2, N2→N3, N3→N4.',
          columns: [
            { id: 'child_doc_number', label: 'Doc Number', type: 'text', required: true, width: 'md' },
            { id: 'child_doc_title', label: 'Title', type: 'text', required: true, width: 'lg' },
            { id: 'child_doc_level', label: 'Level', type: 'select', required: true, width: 'sm',
              options: ['N1', 'N2', 'N3', 'N4'] },
            { id: 'child_doc_status', label: 'Status', type: 'select', required: false, width: 'sm',
              options: ['Draft', 'In Review', 'Approved', 'Obsolete'] },
          ],
        },

        // ── Cross-References ──
        {
          id: 'cross_references',
          name: 'crossReferences',
          label: 'Cross-References / References croisees',
          type: 'repeater',
          helpText: 'List related documents that are referenced within this document (not hierarchical parents/children).',
          columns: [
            { id: 'xref_number', label: 'Document Number', type: 'text', required: true, width: 'md' },
            { id: 'xref_title', label: 'Title', type: 'text', required: true, width: 'lg' },
            { id: 'xref_section', label: 'Referenced Section', type: 'text', required: false, width: 'md' },
          ],
        },

        // ── N1 specific: Regulatory Mapping ──
        {
          id: 'n1_clause_mapping',
          name: 'n1ClauseMapping',
          label: 'Regulatory Clause Mapping / Cartographie des clauses reglementaires',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          helpText: 'N1: Map each section of this policy to specific regulatory clauses.',
          normClause: '4.2.3',
          columns: [
            { id: 'policy_section', label: 'Policy Section', type: 'text', required: true, width: 'md' },
            { id: 'iso_clause', label: 'ISO 13485 Clause', type: 'text', required: true, width: 'sm' },
            { id: 'fda_clause', label: 'FDA 21 CFR Ref', type: 'text', required: false, width: 'sm' },
            { id: 'mdr_ref', label: 'MDR/IVDR Ref', type: 'text', required: false, width: 'sm' },
          ],
          minRows: 2,
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Review & Approval Cycle
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Review & Approval Cycle / Cycle de revue et approbation',
      description: 'Define review frequency, approval workflow, and retention. Review requirements differ by level.',
      normClause: 'ISO 13485 4.2.3(b)(c) / FDA 21 CFR 820.40',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'review_frequency',
          name: 'reviewFrequency',
          label: 'Review Frequency / Frequence de revue',
          type: 'select',
          required: true,
          options: [
            'Annual',
            'Biennial (every 2 years)',
            'Every 3 years',
            'Every 5 years',
            'Event-driven (after significant change)',
            'Continuous (rolling review)',
          ],
          helpText: 'How often must this document be reviewed? N1 policies typically every 3 years; N2 SOPs annually; N3/N4 as needed.',
          normClause: '4.2.3(b)',
        },
        {
          id: 'next_review_date',
          name: 'nextReviewDate',
          label: 'Next Scheduled Review Date',
          type: 'date',
          required: true,
          helpText: 'Date by which the next review must be completed',
          normClause: '4.2.3(b)',
        },
        {
          id: 'retention_period',
          name: 'retentionPeriod',
          label: 'Retention Period / Periode de conservation',
          type: 'select',
          required: true,
          options: [
            '5 years',
            '7 years',
            '10 years',
            '15 years (device lifetime + 2 years per ISO 13485)',
            '25 years (implantable devices)',
            'Lifetime of device + 2 years',
          ],
          helpText: 'How long must records of this document be retained? Per ISO 13485 4.2.4, at least the lifetime of the medical device plus 2 years.',
          normClause: '4.2.4',
        },
        {
          id: 'review_method',
          name: 'reviewMethod',
          label: 'Review Method / Methode de revue',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: [
            'Peer Review',
            'Cross-Functional Review Committee',
            'Management Review',
            'Regulatory Review',
            'External Expert Review',
            'Automated Review (data integrity check)',
          ],
          helpText: 'How will changes to this document be reviewed before approval?',
          normClause: '4.2.3(c)',
        },
        {
          id: 'approval_workflow',
          name: 'approvalWorkflow',
          label: 'Approval Workflow / Workflow d\'approbation',
          type: 'repeater',
          required: true,
          helpText: 'Define the approval chain. Each step requires a named role/person. Documents cannot be approved without completing all steps.',
          normClause: '4.2.3(c) / 21 CFR Part 11',
          columns: [
            { id: 'wf_step', label: 'Step #', type: 'text', required: true, width: 'sm' },
            { id: 'wf_role', label: 'Role', type: 'select', required: true, width: 'md',
              options: ['Author', 'Reviewer', 'QA Approval', 'Department Head', 'Regulatory Affairs', 'Management Representative', 'External Reviewer'] },
            { id: 'wf_assignee', label: 'Assigned To', type: 'user_select', required: true, width: 'md' },
            { id: 'wf_required', label: 'Mandatory?', type: 'checkbox', required: false, width: 'sm' },
          ],
          minRows: 2,
        },

        // ── N1 specific: Management Review ──
        {
          id: 'n1_management_review',
          name: 'n1ManagementReview',
          label: 'Requires Management Review?',
          type: 'yes_no_na',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          helpText: 'N1: Top-level policies must be reviewed by management per clause 5.6',
          normClause: '5.6',
        },
        {
          id: 'n1_mgmt_review_justification',
          name: 'n1MgmtReviewJustification',
          label: 'Management Review Justification',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          helpText: 'N1: Explain how and when this policy will be reviewed by top management.',
          placeholder: 'This policy will be reviewed during the annual Management Review meeting...',
        },

        // ── N4 specific: Validation Workflow ──
        {
          id: 'n4_validation_workflow',
          name: 'n4ValidationWorkflow',
          label: 'Record Validation Workflow / Workflow de validation de l\'enregistrement',
          type: 'section_header',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
        },
        {
          id: 'n4_generates_records',
          name: 'n4GeneratesRecords',
          label: 'This form generates records (instances)',
          type: 'checkbox',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          helpText: 'N4: Check if this form/record template will generate individual record instances when used. Each instance follows its own validation workflow.',
          normClause: '4.2.4',
        },
        {
          id: 'n4_record_lifecycle',
          name: 'n4RecordLifecycle',
          label: 'Record Lifecycle / Cycle de vie de l\'enregistrement',
          type: 'select',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          options: [
            'Draft → Review → Approved → Archived',
            'Draft → QA Review → Approved → Archived',
            'Draft → Dual Review → Approved → Archived',
            'Immediate (auto-approved with e-signature)',
            'Event-triggered (created on event, reviewed post-creation)',
          ],
          helpText: 'N4: Define the validation workflow that generated records must follow. Records cannot be used operationally until approved.',
          normClause: '4.2.4 / 21 CFR Part 11',
        },
        {
          id: 'n4_record_template_name',
          name: 'n4RecordTemplateName',
          label: 'Generated Record Template Name / Nom du template genere',
          type: 'text',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          helpText: 'N4: Name for the record template that will be generated from this form. Used as prefix for instance numbering.',
          placeholder: 'e.g. BATCH-RECORD, INSPECTION-REPORT, CALIBRATION-RECORD',
        },
        {
          id: 'n4_auto_numbering',
          name: 'n4AutoNumbering',
          label: 'Auto-Numbering Format / Format de numerotation automatique',
          type: 'text',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          helpText: 'N4: Format for automatically numbering generated record instances. Use {YYYY} for year, {NNN} for sequential number.',
          placeholder: 'REC-{YYYY}-{NNN}, BR-{YYYY}-{NNN}, CAL-{YYYY}-{NNN}',
        },
        {
          id: 'n4_closure_required_fields',
          name: 'n4ClosureRequiredFields',
          label: 'Closure Required Fields / Champs obligatoires pour cloture',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          helpText: 'N4: Define which fields must be completed before a record instance can be closed/archived. Per 4.2.4, records must be complete.',
          normClause: '4.2.4',
          columns: [
            { id: 'closure_field_name', label: 'Field Name', type: 'text', required: true, width: 'md' },
            { id: 'closure_field_type', label: 'Field Type', type: 'select', required: true, width: 'sm',
              options: ['text', 'number', 'date', 'select', 'checkbox', 'textarea', 'signature', 'file'] },
            { id: 'closure_field_required', label: 'Required?', type: 'checkbox', required: false, width: 'sm' },
          ],
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Content & Structure
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Content & Structure / Contenu & Structure',
      description: 'Define the structure and key content areas of the document. Structure differs significantly by level.',
      normClause: 'ISO 13485 4.2.3',
      collapsible: true,
      fields: [
        // ── N1: Policy Structure ──
        {
          id: 'n1_policy_sections',
          name: 'n1PolicySections',
          label: 'Policy Sections / Sections de la politique',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          helpText: 'N1: Define the sections of this policy document. Each section should map to a regulatory clause.',
          normClause: '4.2.3',
          columns: [
            { id: 'section_num', label: 'Section #', type: 'text', required: true, width: 'sm' },
            { id: 'section_title', label: 'Section Title', type: 'text', required: true, width: 'lg' },
            { id: 'section_clause', label: 'Regulatory Clause', type: 'text', required: true, width: 'md' },
            { id: 'section_summary', label: 'Summary', type: 'textarea', required: false, width: 'lg' },
          ],
          minRows: 3,
        },

        // ── N2: SOP Structure ──
        {
          id: 'n2_sop_sections',
          name: 'n2SopSections',
          label: 'SOP Sections / Sections de la procedure',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N2 — SOP / Procedure' },
          required: true,
          helpText: 'N2: Define the sections of this SOP. Must include: Purpose, Scope, Definitions, Responsibilities, Procedure, References, Attachments.',
          normClause: '4.2.3',
          columns: [
            { id: 'sop_section_num', label: 'Section #', type: 'text', required: true, width: 'sm' },
            { id: 'sop_section_title', label: 'Section Title', type: 'text', required: true, width: 'lg' },
            { id: 'sop_section_type', label: 'Type', type: 'select', required: true, width: 'sm',
              options: ['Mandatory', 'Conditional', 'Informative'] },
            { id: 'sop_section_content', label: 'Key Content Summary', type: 'textarea', required: false, width: 'lg' },
          ],
          minRows: 5,
        },
        {
          id: 'n2_definitions',
          name: 'n2Definitions',
          label: 'Key Definitions / Definitions cles',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N2 — SOP / Procedure' },
          helpText: 'N2: Define technical terms and acronyms used in this SOP.',
          columns: [
            { id: 'def_term', label: 'Term', type: 'text', required: true, width: 'md' },
            { id: 'def_acronym', label: 'Acronym', type: 'text', required: false, width: 'sm' },
            { id: 'def_definition', label: 'Definition', type: 'textarea', required: true, width: 'lg' },
          ],
        },

        // ── N3: WI Step-by-Step ──
        {
          id: 'n3_steps',
          name: 'n3Steps',
          label: 'Step-by-Step Instructions / Instructions etape par etape',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N3 — WI / Instruction de travail' },
          required: true,
          helpText: 'N3: Define each step of the work instruction in sequence. Be precise and unambiguous.',
          normClause: '4.2.3 / 7.5.1',
          columns: [
            { id: 'step_num', label: 'Step #', type: 'text', required: true, width: 'sm' },
            { id: 'step_action', label: 'Action', type: 'textarea', required: true, width: 'lg' },
            { id: 'step_responsibility', label: 'Who', type: 'select', required: true, width: 'sm',
              options: ['Operator', 'Supervisor', 'QA', 'QC', 'Maintenance', 'Engineer'] },
            { id: 'step_acceptance', label: 'Acceptance Criteria', type: 'text', required: false, width: 'md' },
            { id: 'step_critical', label: 'Critical Step?', type: 'checkbox', required: false, width: 'sm' },
            { id: 'step_record', label: 'Record Required', type: 'select', required: false, width: 'sm',
              options: ['Yes', 'No', 'If deviation'] },
          ],
          minRows: 3,
        },
        {
          id: 'n3_equipment_materials',
          name: 'n3EquipmentMaterials',
          label: 'Equipment & Materials Required / Equipements & Materiaux requis',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N3 — WI / Instruction de travail' },
          helpText: 'N3: List all equipment, tools, and materials required to perform this work instruction.',
          columns: [
            { id: 'equip_name', label: 'Equipment/Material', type: 'text', required: true, width: 'lg' },
            { id: 'equip_id', label: 'ID / Reference', type: 'text', required: false, width: 'md' },
            { id: 'equip_calibration', label: 'Calibration Required?', type: 'checkbox', required: false, width: 'sm' },
            { id: 'equip_spec', label: 'Specification', type: 'text', required: false, width: 'md' },
          ],
        },

        // ── N4: Form Fields Definition ──
        {
          id: 'n4_form_fields',
          name: 'n4FormFields',
          label: 'Form Fields Definition / Definition des champs du formulaire',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          helpText: 'N4: Define each field of this form/record template. Each field becomes part of the generated record instances.',
          normClause: '4.2.4 / 21 CFR Part 11',
          columns: [
            { id: 'field_name', label: 'Field Name', type: 'text', required: true, width: 'md' },
            { id: 'field_label', label: 'Label', type: 'text', required: true, width: 'md' },
            { id: 'field_type', label: 'Type', type: 'select', required: true, width: 'sm',
              options: ['text', 'number', 'date', 'select', 'checkbox', 'textarea', 'signature', 'file', 'table', 'user_select'] },
            { id: 'field_required', label: 'Required?', type: 'checkbox', required: false, width: 'sm' },
            { id: 'field_default', label: 'Default Value', type: 'text', required: false, width: 'md' },
            { id: 'field_validation', label: 'Validation Rule', type: 'text', required: false, width: 'md' },
          ],
          minRows: 3,
        },
        {
          id: 'n4_form_sections',
          name: 'n4FormSections',
          label: 'Form Sections / Sections du formulaire',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          helpText: 'N4: Group form fields into logical sections for the generated record template.',
          columns: [
            { id: 'form_section_num', label: 'Section #', type: 'text', required: true, width: 'sm' },
            { id: 'form_section_title', label: 'Section Title', type: 'text', required: true, width: 'lg' },
            { id: 'form_section_fields', label: 'Fields (IDs)', type: 'text', required: true, width: 'lg' },
            { id: 'form_section_required', label: 'Required for Closure?', type: 'checkbox', required: false, width: 'sm' },
          ],
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Training & Competence
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Training & Competence / Formation & Competence',
      description: 'Define training requirements for document users. N1/N2 typically require formal training; N3 may require practical demonstration; N4 records training completion.',
      normClause: 'ISO 13485 6.2',
      collapsible: true,
      defaultCollapsed: true,
      fields: [
        {
          id: 'training_required',
          name: 'trainingRequired',
          label: 'Training Required Before Use?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Must personnel be trained on this document before they can use it operationally?',
          normClause: '6.2',
        },
        {
          id: 'training_type',
          name: 'trainingType',
          label: 'Training Type / Type de formation',
          type: 'select',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          required: true,
          options: [
            'Read & Understand (self-study)',
            'Classroom Training',
            'On-the-Job Training (OJT)',
            'Practical Demonstration',
            'Online/e-Learning Module',
            'Competency Assessment',
            'Combination (specify in comments)',
          ],
          helpText: 'What type of training is required? N1/N2: typically classroom or read & understand; N3: OJT or demonstration; N4: read & understand.',
          normClause: '6.2',
        },
        {
          id: 'training_target_audience',
          name: 'trainingTargetAudience',
          label: 'Target Audience / Public cible',
          type: 'multi_select',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          required: true,
          options: [
            'Production Operators',
            'QA Inspectors',
            'QC Analysts',
            'Maintenance Technicians',
            'Supervisors',
            'Department Heads',
            'All Staff',
            'Engineering',
            'Regulatory Affairs',
            'Management',
          ],
          helpText: 'Who must be trained on this document?',
          normClause: '6.2',
        },
        {
          id: 'training_competency_criteria',
          name: 'trainingCompetencyCriteria',
          label: 'Competency Criteria / Criteres de competence',
          type: 'textarea',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          helpText: 'How will you verify that personnel are competent after training? Quiz, practical test, observation...',
          placeholder: 'Competency is assessed by: [method]. Minimum score: [threshold]. Reassessment frequency: [period].',
          normClause: '6.2',
        },
        {
          id: 'retraining_trigger',
          name: 'retrainingTrigger',
          label: 'Retraining Trigger / Declencheur de reformation',
          type: 'multi_select',
          showIf: { fieldId: 'training_required', operator: 'equals', value: 'Yes' },
          options: [
            'Document revision',
            'Regulatory change',
            'Non-conformance related to document',
            'Audit finding',
            'Periodic (annual refresher)',
            'Role change / new hire',
            'Process change',
          ],
          helpText: 'What events require retraining on this document?',
          normClause: '6.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 7 — Change Control & Revision History
    // ══════════════════════════════════════════════════════════════
    {
      id: 's7',
      order: 7,
      title: '7. Change Control & Revision History / Maitrise des changements & Historique',
      description: 'Track all revisions and changes. Every modification must be documented with justification and approval.',
      normClause: 'ISO 13485 4.2.3(c) / 8.5.2',
      collapsible: true,
      defaultCollapsed: true,
      fields: [
        {
          id: 'change_control_required',
          name: 'changeControlRequired',
          label: 'Change Control Required for Revisions?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Must a formal Change Control be initiated before revising this document? N1/N2: typically yes; N3/N4: depends on impact.',
          normClause: '4.2.3(c)',
        },
        {
          id: 'change_impact_assessment',
          name: 'changeImpactAssessment',
          label: 'Change Impact Assessment Required?',
          type: 'yes_no_na',
          showIf: { fieldId: 'change_control_required', operator: 'equals', value: 'Yes' },
          helpText: 'Must an impact assessment be performed before approving changes? Assesses effect on processes, products, training, other documents.',
          normClause: '8.5.2',
        },
        {
          id: 'revision_history',
          name: 'revisionHistory',
          label: 'Revision History / Historique des revisions',
          type: 'repeater',
          helpText: 'Document every revision with version, date, description, and approver.',
          normClause: '4.2.3(c)',
          columns: [
            { id: 'rev_version', label: 'Version', type: 'text', required: true, width: 'sm' },
            { id: 'rev_date', label: 'Date', type: 'date', required: true, width: 'sm' },
            { id: 'rev_description', label: 'Change Description', type: 'textarea', required: true, width: 'lg' },
            { id: 'rev_justification', label: 'Justification', type: 'textarea', required: true, width: 'lg' },
            { id: 'rev_author', label: 'Author', type: 'user_select', required: true, width: 'md' },
            { id: 'rev_approver', label: 'Approved By', type: 'user_select', required: true, width: 'md' },
          ],
        },
        {
          id: 'n2_n3_affected_documents',
          name: 'affectedDocuments',
          label: 'Other Documents Affected by This Change',
          type: 'repeater',
          showIf: { fieldId: 'doc_level', operator: 'not_equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          helpText: 'N1-N3: List other documents that must be updated when this document is revised. Ensures hierarchy consistency.',
          columns: [
            { id: 'affected_doc_number', label: 'Doc Number', type: 'text', required: true, width: 'md' },
            { id: 'affected_doc_title', label: 'Title', type: 'text', required: true, width: 'lg' },
            { id: 'affected_change_type', label: 'Change Type', type: 'select', required: true, width: 'sm',
              options: ['Minor Update', 'Major Revision', 'Obsolescence', 'New Document'] },
          ],
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 8 — Approval & Signatures
    // ══════════════════════════════════════════════════════════════
    {
      id: 's8',
      order: 8,
      title: '8. Approval & Electronic Signatures / Approbation & Signatures electroniques',
      description: 'Final approval with electronic signatures per 21 CFR Part 11. Approval requirements vary by document level.',
      normClause: 'ISO 13485 4.2.3(c) / FDA 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'approval_readiness',
          name: 'approvalReadiness',
          label: 'Document Ready for Approval?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Confirm that all sections are complete, all reviewers have provided feedback, and the document is ready for formal approval.',
          normClause: '4.2.3(c)',
        },
        {
          id: 'approval_readiness_checklist',
          name: 'approvalReadinessChecklist',
          label: 'Approval Readiness Checklist',
          type: 'section_header',
          showIf: { fieldId: 'approval_readiness', operator: 'equals', value: 'Yes' },
        },
        {
          id: 'check_content_complete',
          name: 'checkContentComplete',
          label: 'All content sections are complete and reviewed',
          type: 'checkbox',
          showIf: { fieldId: 'approval_readiness', operator: 'equals', value: 'Yes' },
          required: true,
        },
        {
          id: 'check_hierarchy_valid',
          name: 'checkHierarchyValid',
          label: 'Parent/child document hierarchy is correct and up to date',
          type: 'checkbox',
          showIf: { fieldId: 'approval_readiness', operator: 'equals', value: 'Yes' },
          required: true,
          normClause: '4.2.3',
        },
        {
          id: 'check_references_valid',
          name: 'checkReferencesValid',
          label: 'All referenced documents exist and are currently approved',
          type: 'checkbox',
          showIf: { fieldId: 'approval_readiness', operator: 'equals', value: 'Yes' },
          required: true,
          normClause: '4.2.3',
        },
        {
          id: 'check_training_planned',
          name: 'checkTrainingPlanned',
          label: 'Training plan is defined (if training is required)',
          type: 'checkbox',
          showIf: { fieldId: 'approval_readiness', operator: 'equals', value: 'Yes' },
        },
        {
          id: 'check_data_integrity',
          name: 'checkDataIntegrity',
          label: 'Data integrity (ALCOA+) requirements are addressed',
          type: 'checkbox',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          normClause: '21 CFR Part 11',
        },
        {
          id: 'check_record_workflow',
          name: 'checkRecordWorkflow',
          label: 'Record validation workflow is defined and complete',
          type: 'checkbox',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          normClause: '4.2.4',
        },

        // ── Author Signature ──
        {
          id: 'author_signature',
          name: 'authorSignature',
          label: 'Author Signature / Signature de l\'auteur',
          type: 'signature',
          required: true,
          helpText: 'Electronic signature confirming authorship and accuracy of content. Per 21 CFR Part 11, this constitutes a legally binding signature.',
          normClause: '21 CFR 11.200',
        },

        // ── N1: Additional Management Signature ──
        {
          id: 'n1_management_signature',
          name: 'n1ManagementSignature',
          label: 'Management Representative Signature / Signature du Representant de la Direction',
          type: 'signature',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N1 — Policy / Politique' },
          required: true,
          requiredForClosure: true,
          helpText: 'N1: Top-level policies require Management Representative approval per clause 5.6.',
          normClause: '5.6 / 21 CFR 11.200',
        },

        // ── QA Approval Signature ──
        {
          id: 'approval_signature',
          name: 'approvalSignature',
          label: 'QA Approval Signature / Signature d\'approbation QA',
          type: 'signature',
          required: true,
          requiredForClosure: true,
          helpText: 'QA approval confirming compliance with QMS requirements. This is the final step before the document becomes effective.',
          normClause: '4.2.3(c) / 21 CFR 11.200',
        },

        // ── N4: Record Validation Signature ──
        {
          id: 'n4_record_validation_signature',
          name: 'n4RecordValidationSignature',
          label: 'Record Template Validation Signature / Signature de validation du template',
          type: 'signature',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          required: true,
          requiredForClosure: true,
          helpText: 'N4: Additional signature confirming that the form/record template is validated and ready to generate record instances. Each generated instance will undergo its own approval workflow.',
          normClause: '4.2.4 / 21 CFR 11.200',
        },

        {
          id: 'effective_date',
          name: 'effectiveDate',
          label: 'Effective Date / Date d\'effet',
          type: 'date',
          required: true,
          requiredForClosure: true,
          readOnly: true,
          helpText: 'Auto-filled upon final approval signature',
          normClause: '4.2.3(c)',
        },

        // ── N4: Generated Record Info ──
        {
          id: 'n4_record_generation_summary',
          name: 'n4RecordGenerationSummary',
          label: 'Record Generation Summary / Resume de generation des enregistrements',
          type: 'section_header',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
        },
        {
          id: 'n4_record_instance_note',
          name: 'n4RecordInstanceNote',
          label: 'Upon approval, this N4 form template will generate record instances. Each instance will: (1) be auto-numbered, (2) follow the defined validation workflow (Draft→Review→Approved), (3) require its own electronic signatures, (4) be retained per the defined retention period. Generated records are subject to 21 CFR Part 11 and ISO 13485 4.2.4 requirements.',
          type: 'textarea',
          showIf: { fieldId: 'doc_level', operator: 'equals', value: 'N4 — Form/Record / Formulaire-Enregistrement' },
          readOnly: true,
          defaultValue: 'Upon approval, this N4 form template will generate record instances subject to the validation workflow defined in Section 4. Each generated record instance follows: Draft → Review → Approved → Archived lifecycle with electronic signatures per 21 CFR Part 11.',
        },
      ],
    },
  ],
};
