/**
 * forms-form-template.ts
 * ─────────────────────────
 * Template Forms (Form Template Registration) complet conforme
 * ISO 13485:2016 §4.2.3 / §4.2.4 / FDA 21 CFR Part 11 / ICH Q7
 *
 * 6 sections - 40+ champs - logique conditionnelle - champs calcules
 * Utilise pour enregistrer / creer un nouveau modele de formulaire standardise dans le QMS.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const FORMS_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-forms-001',
  documentId: 'doc-tmr-forms-001',
  title: 'Forms — Form Template Registration',
  version: '1.0',
  isActive: true,
  recordTarget: 'Documents',
  normReference: 'ISO 13485:2016 §4.2.3 / §4.2.4 / FDA 21 CFR Part 11 / ICH Q7',
  retentionYears: 5,
  closureRequiredFields: [
    'field_definitions',
    'requires_approval',
    'template_status',
    'approved_by',
    'approval_signature',
    'activation_date',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Template Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Template Identification',
      description: 'Identify the form template with a unique number, title, version and ownership.',
      normClause: 'ISO 13485 4.2.3',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'template_number',
          name: 'templateNumber',
          label: 'Template Number',
          type: 'text',
          readOnly: true,
          helpText: 'Auto-generated form template number',
          normClause: '4.2.3',
        },
        {
          id: 'creation_date',
          name: 'creationDate',
          label: 'Creation Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
        {
          id: 'title',
          name: 'title',
          label: 'Title',
          type: 'text',
          required: true,
          validation: { minLength: 5, maxLength: 200 },
          placeholder: 'Form template title',
          normClause: '4.2.3',
        },
        {
          id: 'version',
          name: 'version',
          label: 'Version',
          type: 'text',
          required: true,
          defaultValue: '1.0',
          placeholder: 'e.g., 1.0',
          normClause: '4.2.3',
        },
        {
          id: 'category',
          name: 'category',
          label: 'Category',
          type: 'select',
          required: true,
          options: [
            'Quality Control',
            'Quality Assurance',
            'Manufacturing',
            'Laboratory',
            'Regulatory',
            'Training',
            'Supply Chain',
            'Other',
          ],
          normClause: '4.2.3',
        },
        {
          id: 'description',
          name: 'description',
          label: 'Description',
          type: 'textarea',
          required: true,
          placeholder: 'Describe the purpose and scope of this form template...',
          normClause: '4.2.4',
        },
        {
          id: 'linked_document_id',
          name: 'linkedDocumentId',
          label: 'Linked Document Reference',
          type: 'text',
          placeholder: 'Linked controlled document reference',
          helpText: 'Reference to the controlled document this form supports',
          normClause: '4.2.3',
        },
        {
          id: 'template_owner',
          name: 'templateOwner',
          label: 'Template Owner',
          type: 'user_select',
          required: true,
          helpText: 'Person responsible for maintaining this form template',
          normClause: '4.2.3',
        },
        {
          id: 'department',
          name: 'department',
          label: 'Department',
          type: 'select',
          required: true,
          options: ['QA', 'QC', 'Production', 'Regulatory', 'Warehouse', 'Engineering', 'R&D', 'Management'],
          normClause: '4.2.3',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Field Definitions
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Field Definitions',
      description: 'Define each field that makes up the form template, including its type, label and requirements.',
      normClause: 'ISO 13485 4.2.4',
      requiredForClosure: true,
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'field_definitions',
          name: 'fieldDefinitions',
          label: 'Field Definitions',
          type: 'repeater',
          required: true,
          requiredForClosure: true,
          columns: [
            { id: 'field_name',      label: 'Field Name',  type: 'text',    required: true, width: 'md' },
            { id: 'field_label',     label: 'Label',       type: 'text',    required: true, width: 'md' },
            { id: 'field_type',      label: 'Type',        type: 'select',  required: true, width: 'sm',
              options: ['text', 'number', 'date', 'select', 'checkbox', 'textarea', 'signature', 'table', 'rich_text', 'user_select', 'multi_select', 'file', 'rating', 'repeater', 'yes_no_na', 'date_range', 'calculated'] },
            { id: 'field_required',  label: 'Required',    type: 'checkbox', required: false, width: 'sm' },
            { id: 'field_placeholder', label: 'Placeholder', type: 'text',  required: false, width: 'md' },
          ],
          minRows: 1,
          helpText: 'Define each field in the form template. Minimum 1 field required.',
          normClause: '4.2.4',
        },
        {
          id: 'total_field_count',
          name: 'totalFieldCount',
          label: 'Total Field Count',
          type: 'calculated',
          calculation: {
            sourceFields: ['field_definitions'],
            formula: 'custom',
            expression: 'field_definitions.length',
          },
          readOnly: true,
          helpText: 'Auto-calculated from field definitions',
          normClause: '4.2.4',
        },
        {
          id: 'signature_fields_count',
          name: 'signatureFieldsCount',
          label: 'Signature Fields Count',
          type: 'number',
          readOnly: true,
          helpText: 'Auto-detected from field types',
          normClause: '21 CFR 11.200',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Field Validation & Configuration
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Field Validation & Configuration',
      description: 'Add validation rules and conditional logic to control field behavior and data integrity.',
      normClause: 'ISO 13485 4.2.4',
      collapsible: true,
      fields: [
        {
          id: 'validation_rules',
          name: 'validationRules',
          label: 'Validation Rules',
          type: 'repeater',
          columns: [
            { id: 'val_field_ref', label: 'Field #',     type: 'text',   required: true,  width: 'sm' },
            { id: 'val_type',      label: 'Validation',  type: 'select', required: true,  width: 'md',
              options: ['Required', 'Min Length', 'Max Length', 'Min Value', 'Max Value', 'Pattern (Regex)', 'Options List'] },
            { id: 'val_value',     label: 'Value',       type: 'text',   required: false, width: 'md' },
            { id: 'val_message',   label: 'Error Message', type: 'text', required: false, width: 'lg' },
          ],
          helpText: 'Add validation rules for fields defined above',
          normClause: '4.2.4',
        },
        {
          id: 'conditional_logic',
          name: 'conditionalLogic',
          label: 'Conditional Logic Rules',
          type: 'repeater',
          columns: [
            { id: 'cond_trigger_field', label: 'Trigger Field', type: 'text',   required: true,  width: 'md' },
            { id: 'cond_operator',      label: 'Operator',      type: 'select', required: true,  width: 'sm',
              options: ['equals', 'not_equals', 'contains', 'is_filled'] },
            { id: 'cond_value',         label: 'Value',         type: 'text',   required: false, width: 'md' },
            { id: 'cond_show_field',    label: 'Show Field',    type: 'text',   required: true,  width: 'md' },
          ],
          helpText: 'Define conditional field visibility rules',
          normClause: '4.2.4',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Workflow & Rules
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Workflow & Rules',
      description: 'Configure the approval workflow, electronic signature requirements and versioning rules.',
      normClause: 'ISO 13485 4.2.3 / 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'requires_approval',
          name: 'requiresApproval',
          label: 'Requires Approval?',
          type: 'yes_no_na',
          required: true,
          defaultValue: 'Yes',
          helpText: 'Indicate whether this form template requires approval before activation',
          normClause: '4.2.3',
        },
        {
          id: 'approval_workflow',
          name: 'approvalWorkflow',
          label: 'Approval Workflow',
          type: 'select',
          showIf: { fieldId: 'requires_approval', operator: 'equals', value: 'Yes' },
          options: [
            'Single Approver',
            'Sequential Approval',
            'Parallel Approval',
            'Committee Review',
          ],
          helpText: 'Select the type of approval workflow for this template',
          normClause: '4.2.3',
        },
        {
          id: 'allow_draft_saves',
          name: 'allowDraftSaves',
          label: 'Allow Draft Saves',
          type: 'checkbox',
          defaultValue: true,
          helpText: 'Allow users to save incomplete forms as drafts',
          normClause: '4.2.3',
        },
        {
          id: 'lock_after_submission',
          name: 'lockAfterSubmission',
          label: 'Lock After Submission',
          type: 'checkbox',
          defaultValue: true,
          helpText: 'Lock the record after submission to prevent unauthorized changes',
          normClause: '21 CFR 11.10',
        },
        {
          id: 'e_signature_required',
          name: 'eSignatureRequired',
          label: 'E-Signature Required?',
          type: 'yes_no_na',
          required: true,
          normClause: '21 CFR 11.200',
          helpText: 'Require electronic signature(s) when completing this form',
        },
        {
          id: 'part11_compliance',
          name: 'part11Compliance',
          label: '21 CFR Part 11 Compliance',
          type: 'checkbox',
          helpText: 'Enable full 21 CFR Part 11 compliance features',
          normClause: '21 CFR 11.10',
        },
        {
          id: 'auto_version_on_change',
          name: 'autoVersionOnChange',
          label: 'Auto-Version on Change',
          type: 'checkbox',
          defaultValue: true,
          helpText: 'Automatically increment version when template is modified',
          normClause: '4.2.3',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Compliance & Retention
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Compliance & Retention',
      description: 'Define regulatory references, data classification, retention policy and data integrity controls.',
      normClause: 'ISO 13485 4.2.4 / 21 CFR Part 11',
      collapsible: true,
      fields: [
        {
          id: 'regulatory_reference',
          name: 'regulatoryReference',
          label: 'Regulatory Reference',
          type: 'text',
          placeholder: 'e.g., ISO 13485:2016 §4.2.4, 21 CFR 211.188',
          helpText: 'Applicable regulatory or normative reference for this form template',
          normClause: '4.2.4',
        },
        {
          id: 'retention_period',
          name: 'retentionPeriod',
          label: 'Retention Period',
          type: 'select',
          required: true,
          options: ['1 Year', '3 Years', '5 Years', '7 Years', '10 Years', 'Product Lifetime'],
          helpText: 'Minimum retention period for records created from this template',
          normClause: '4.2.4',
        },
        {
          id: 'data_classification',
          name: 'dataClassification',
          label: 'Data Classification',
          type: 'select',
          required: true,
          options: ['Internal', 'Confidential', 'Regulatory', 'GxP Critical'],
          helpText: 'Classify the sensitivity level of data captured by this form',
          normClause: '4.2.4',
        },
        {
          id: 'audit_trail_enabled',
          name: 'auditTrailEnabled',
          label: 'Audit Trail Enabled',
          type: 'checkbox',
          defaultValue: true,
          helpText: 'All changes to form data are tracked with who, when, and what changed',
          normClause: '21 CFR 11.10(e)',
        },
        {
          id: 'print_friendly_layout',
          name: 'printFriendlyLayout',
          label: 'Print-Friendly Layout',
          type: 'checkbox',
          helpText: 'Optimize layout for printing',
          normClause: '4.2.4',
        },
        {
          id: 'periodic_review_interval',
          name: 'periodicReviewInterval',
          label: 'Periodic Review Interval',
          type: 'select',
          options: ['6 months', '12 months', '24 months', '36 months'],
          helpText: 'How often this template must be reviewed for continued suitability',
          normClause: '4.2.3',
        },
        {
          id: 'next_review_date',
          name: 'nextReviewDate',
          label: 'Next Review Date',
          type: 'date',
          helpText: 'Automatically calculated from review interval',
          normClause: '4.2.3',
        },
        {
          id: 'data_integrity_controls',
          name: 'dataIntegrityControls',
          label: 'Data Integrity Controls',
          type: 'multi_select',
          options: [
            'ALCOA+ Principles',
            'Audit Trail',
            'Electronic Signatures',
            'Access Controls',
            'Data Backup',
            'Change History',
          ],
          helpText: 'Select data integrity controls applicable to this form template',
          normClause: '21 CFR 11.10 / ICH Q7',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Review & Activation
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Review & Activation',
      description: 'Review, approve and activate the form template for use in the QMS.',
      normClause: 'ISO 13485 4.2.3 / 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'template_status',
          name: 'templateStatus',
          label: 'Template Status',
          type: 'select',
          required: true,
          options: ['Draft', 'Under Review', 'Active', 'Superseded', 'Retired'],
          normClause: '4.2.3',
        },
        {
          id: 'review_notes',
          name: 'reviewNotes',
          label: 'Review Notes',
          type: 'textarea',
          placeholder: 'Review findings, comments, required changes...',
          helpText: 'Document review findings and any required modifications',
          normClause: '4.2.3',
        },
        {
          id: 'approved_by',
          name: 'approvedBy',
          label: 'Approved By',
          type: 'user_select',
          requiredForClosure: true,
          helpText: 'Designated approver for this form template',
          normClause: '4.2.3',
        },
        {
          id: 'approval_signature',
          name: 'approvalSignature',
          label: 'Approval Signature',
          type: 'signature',
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200',
          readOnly: false,
        },
        {
          id: 'activation_date',
          name: 'activationDate',
          label: 'Activation Date',
          type: 'date',
          readOnly: true,
          requiredForClosure: true,
          helpText: 'Date the template becomes active and available for use',
          normClause: '4.2.3',
        },
        {
          id: 'training_required_for_users',
          name: 'trainingRequiredForUsers',
          label: 'Training Required for Users?',
          type: 'yes_no_na',
          helpText: 'Do users need training before using this form?',
          normClause: '6.2',
        },
        {
          id: 'training_scope',
          name: 'trainingScope',
          label: 'Training Scope',
          type: 'textarea',
          showIf: { fieldId: 'training_required_for_users', operator: 'equals', value: 'Yes' },
          placeholder: 'Describe required training content, target audience and delivery method...',
          helpText: 'Define the scope of training required before users can use this form template',
          normClause: '6.2',
        },
        {
          id: 'superseded_template',
          name: 'supersededTemplate',
          label: 'Superseded Template Reference',
          type: 'text',
          placeholder: 'Reference number of template this replaces, if any',
          helpText: 'If this template replaces an earlier version, reference the superseded template number',
          normClause: '4.2.3',
        },
        {
          id: 'change_summary',
          name: 'changeSummary',
          label: 'Change Summary',
          type: 'textarea',
          placeholder: 'Summary of changes from previous version...',
          helpText: 'Describe what changed compared to the previous version of this template',
          normClause: '4.2.3',
        },
      ],
    },
  ],
};
