/**
 * ncr-form-template.ts
 * ──────────────────────
 * Template NCR (Non-Conformance Report) complet conforme ISO 13485 8.3
 *
 * 6 sections - 45+ champs - logique conditionnelle - champs OOS/OOT
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const NCR_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-ncr-001',
  documentId: 'doc-tmr-ncr-001',   // Document Control approuve TMR-NCR-001
  title: 'Non-Conformance Report (NCR)',
  version: '2.0',
  isActive: true,
  recordTarget: 'NCR',
  normReference: 'ISO 13485:2016 8.3 / FDA 21 CFR 820.90',
  retentionYears: 5,
  closureRequiredFields: [
    'problem_description',
    'severity',
    'containment_action',
    'investigation_summary',
    'disposition',
    'disposition_justification',
    'qa_approval_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Problem Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s1',
      order: 1,
      title: '1. Problem Identification',
      description: 'Clearly identify and describe the non-conformance. Document what was observed, when, and by whom.',
      normClause: 'ISO 13485 8.3(a)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'ncr_number',
          name: 'ncrNumber',
          label: 'NCR Number',
          type: 'text',
          readOnly: true,
          helpText: 'Generated automatically',
          normClause: '4.2.4',
        },
        {
          id: 'ncr_date',
          name: 'ncrDate',
          label: 'NCR Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
        {
          id: 'ncr_type',
          name: 'ncrType',
          label: 'Non-Conformance Type',
          type: 'select',
          required: true,
          options: ['Product', 'Process', 'System', 'Supplier', 'OOS', 'OOT'],
          normClause: '8.3',
          helpText: 'Product: physical defect / Process: deviation from procedure / System: systemic gap / Supplier: incoming material / OOS-OOT: out of specification result',
        },
        {
          id: 'ncr_title',
          name: 'ncrTitle',
          label: 'NCR Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'Short factual description of the non-conformance',
          normClause: '8.3(a)',
        },
        {
          id: 'problem_description',
          name: 'problemDescription',
          label: 'Detailed Problem Description (5W2H)',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 100 },
          helpText: 'Describe: What, Who, When, Where, Why, How, How many. Be factual — no assumptions at this stage.',
          normClause: '8.3(a)',
          placeholder: 'WHAT: Describe the non-conformance observed...\nWHO: Who discovered / who is impacted...\nWHEN: Date / frequency...\nWHERE: Location (site, equipment, process step)...\nHOW MANY: Extent, affected lots, quantity...',
        },
        {
          id: 'severity',
          name: 'severity',
          label: 'Severity Assessment',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: ['Critical', 'Major', 'Minor'],
          helpText: 'Critical = patient safety impact / Major = significant quality deviation / Minor = isolated deviation with no direct impact',
          normClause: '8.3',
        },
        {
          id: 'source',
          name: 'source',
          label: 'Detection Source',
          type: 'select',
          required: true,
          options: [
            'In-Process Inspection',
            'Final QC Testing',
            'Customer Complaint',
            'Internal Audit',
            'Regulatory Audit / Inspection',
            'Supplier COA Review',
            'Environmental Monitoring',
            'Stability Study',
            'OOS Laboratory Investigation',
            'Process Deviation',
            'Management Review',
            'Other',
          ],
          normClause: '8.2.4 / 8.2.5',
        },
        {
          id: 'source_reference',
          name: 'sourceReference',
          label: 'Source Document Reference',
          type: 'text',
          placeholder: 'e.g. Complaint #C-2024-042, Audit AUD-2024-007, Batch Record BN-2024-038',
          helpText: 'Reference number of the record that triggered this NCR',
        },
        {
          id: 'is_oos_oot',
          name: 'isOosOot',
          label: 'Is this an OOS/OOT result?',
          type: 'checkbox',
          helpText: 'Check if this NCR originates from an Out of Specification or Out of Trend analytical result',
        },
        {
          id: 'initiated_by',
          name: 'initiatedBy',
          label: 'Initiated By',
          type: 'user_select',
          required: true,
          readOnly: true,
          helpText: 'Auto-filled from your session',
        },
        {
          id: 'assigned_to',
          name: 'assignedTo',
          label: 'Assigned Investigator',
          type: 'user_select',
          required: true,
          normClause: '8.3(b)',
        },
        {
          id: 'target_date',
          name: 'targetDate',
          label: 'Target Completion Date',
          type: 'date',
          required: true,
          normClause: '8.3',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Product / Process Details
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s2',
      order: 2,
      title: '2. Product / Process Details',
      description: 'Identify the affected product, batch, and process. Link to relevant specifications.',
      normClause: 'ISO 13485 8.3(a)',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'product_name',
          name: 'productName',
          label: 'Product Name / Code',
          type: 'text',
          required: true,
          placeholder: 'e.g. Product X-200, MED-DEVICE-001',
        },
        {
          id: 'lot_number',
          name: 'lotNumber',
          label: 'Lot / Batch Number',
          type: 'text',
          required: true,
          placeholder: 'e.g. BN-2024-038',
          normClause: '7.5.9',
        },
        {
          id: 'quantity_affected',
          name: 'quantityAffected',
          label: 'Quantity Affected',
          type: 'number',
          required: true,
          placeholder: '0',
          validation: { min: 0 },
          helpText: 'Number of units, samples, or batches affected',
        },
        {
          id: 'quantity_produced',
          name: 'quantityProduced',
          label: 'Total Quantity Produced',
          type: 'number',
          placeholder: '0',
          helpText: 'For calculating the percentage affected',
        },
        {
          id: 'process_step',
          name: 'processStep',
          label: 'Process Step / Operation',
          type: 'text',
          placeholder: 'e.g. Filling Line B, Sterilization Cycle 42, QC Release Testing',
        },
        {
          id: 'specification_reference',
          name: 'specificationReference',
          label: 'Applicable Specification',
          type: 'text',
          required: true,
          placeholder: 'e.g. SPEC-PROD-001 Rev.3, USP <1231>, Ph. Eur. 2.4.XX',
          helpText: 'Specification or acceptance criterion that is not met',
          normClause: '7.4.3',
        },
        {
          id: 'equipment_involved',
          name: 'equipmentInvolved',
          label: 'Equipment / Instrument Involved',
          type: 'text',
          placeholder: 'e.g. HPLC-007, Balance B-012, Autoclave A-003',
        },
        {
          id: 'sop_reference',
          name: 'sopReference',
          label: 'Applicable SOP / Work Instruction',
          type: 'text',
          placeholder: 'e.g. SOP-PROD-012 Rev.5',
          normClause: '4.2.3',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — OOS/OOT Investigation (conditional)
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s3',
      order: 3,
      title: '3. OOS/OOT Investigation',
      description: 'Phase 1 (Laboratory Investigation) and Phase 2 (Full-Scale Investigation) per FDA OOS Guidance and EU GMP Annex 15.',
      normClause: 'FDA OOS Guidance / EU GMP Annex 15',
      collapsible: true,
      defaultCollapsed: true,
      fields: [
        {
          id: 'oos_header',
          name: 'oosHeader',
          label: 'This section is only visible when the NCR type is OOS or OOT',
          type: 'section_header',
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
        },
        {
          id: 'analytical_method',
          name: 'analyticalMethod',
          label: 'Analytical Method',
          type: 'text',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          placeholder: 'e.g. HPLC Method QC-M-042 Rev.2',
          normClause: '7.6',
        },
        {
          id: 'measured_value',
          name: 'measuredValue',
          label: 'Measured Value',
          type: 'number',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          placeholder: 'e.g. 92.3',
        },
        {
          id: 'measured_unit',
          name: 'measuredUnit',
          label: 'Unit',
          type: 'text',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          placeholder: 'e.g. %, mg/L, CFU/mL',
        },
        {
          id: 'spec_limit',
          name: 'specLimit',
          label: 'Specification Limit',
          type: 'text',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          placeholder: 'e.g. 95.0-105.0%',
          helpText: 'Acceptance criterion range or upper/lower limit',
        },
        {
          id: 'phase1_investigation',
          name: 'phase1Investigation',
          label: 'Phase 1 — Laboratory Investigation',
          type: 'textarea',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          placeholder: 'Investigate possible laboratory errors: analyst technique, instrument calibration, reagent quality, calculation error...',
          normClause: 'FDA OOS Guidance Phase 1',
        },
        {
          id: 'phase1_conclusion',
          name: 'phase1Conclusion',
          label: 'Phase 1 Conclusion',
          type: 'select',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          options: ['No Error Found', 'Error Found — Assignable Cause Identified', 'Inconclusive — Proceed to Phase 2'],
          normClause: 'FDA OOS Guidance',
        },
        {
          id: 'phase1_assignable_cause',
          name: 'phase1AssignableCause',
          label: 'Assignable Cause Description',
          type: 'textarea',
          showIf: { fieldId: 'phase1_conclusion', operator: 'equals', value: 'Error Found — Assignable Cause Identified' },
          placeholder: 'Describe the assignable laboratory cause and evidence...',
        },
        {
          id: 'phase2_required',
          name: 'phase2Required',
          label: 'Phase 2 Required?',
          type: 'yes_no_na',
          required: true,
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          helpText: 'Phase 2 is required when Phase 1 finds no assignable cause or is inconclusive',
          normClause: 'FDA OOS Guidance Phase 2',
        },
        {
          id: 'phase2_investigation',
          name: 'phase2Investigation',
          label: 'Phase 2 — Full-Scale Investigation',
          type: 'rich_text',
          showIf: { fieldId: 'phase2_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Manufacturing process review, environmental monitoring, raw materials, equipment, personnel, trend analysis...',
          normClause: 'FDA OOS Guidance Phase 2',
        },
        {
          id: 'phase2_conclusion',
          name: 'phase2Conclusion',
          label: 'Phase 2 Conclusion',
          type: 'select',
          showIf: { fieldId: 'phase2_required', operator: 'equals', value: 'Yes' },
          options: ['Invalidated — OOS due to laboratory error', 'Confirmed OOS — Product fails specification', 'Inconclusive — Additional data needed'],
        },
        {
          id: 'reject_lot',
          name: 'rejectLot',
          label: 'Lot Disposition Recommendation',
          type: 'select',
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          options: ['Reject Lot', 'Release Lot with Justification', 'Rework', 'Pending — Additional testing required'],
          normClause: '8.3',
        },
        {
          id: 'oos_evidence',
          name: 'oosEvidence',
          label: 'Attachments — OOS/OOT Evidence',
          type: 'file',
          showIf: { fieldId: 'is_oos_oot', operator: 'equals', value: true },
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx'],
          maxFileSizeMB: 20,
          helpText: 'Chromatograms, analytical reports, calibration certificates...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Containment & Segregation
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s4',
      order: 4,
      title: '4. Containment & Segregation',
      description: 'Immediate actions to contain the non-conformance and prevent further impact on product quality or patients.',
      normClause: 'ISO 13485 8.3(b) / GMP',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'containment_required',
          name: 'containmentRequired',
          label: 'Containment Action Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Quarantine, segregation, process hold, recall, etc.',
          normClause: '8.3(b)',
        },
        {
          id: 'containment_action',
          name: 'containmentAction',
          label: 'Containment Actions Taken',
          type: 'repeater',
          required: true,
          requiredForClosure: true,
          showIf: { fieldId: 'containment_required', operator: 'equals', value: 'Yes' },
          columns: [
            { id: 'ct_action',      label: 'Action',          type: 'textarea',    required: true, width: 'lg' },
            { id: 'ct_responsible', label: 'Responsible',     type: 'user_select', required: true, width: 'md' },
            { id: 'ct_date',        label: 'Completion Date', type: 'date',        required: true, width: 'sm' },
            { id: 'ct_done',        label: 'Completed',       type: 'checkbox',    required: false, width: 'sm' },
          ],
          minRows: 1,
          helpText: 'List each immediate containment action with owner and completion date',
        },
        {
          id: 'quarantine_status',
          name: 'quarantineStatus',
          label: 'Quarantine Status',
          type: 'select',
          options: ['Full quarantine — all lots sequestered', 'Partial quarantine — specific lots', 'Not quarantined — justification required', 'N/A — no physical product involved'],
          normClause: '8.3(b)',
        },
        {
          id: 'quarantine_justification',
          name: 'quarantineJustification',
          label: 'Justification (if not quarantined)',
          type: 'textarea',
          showIf: { fieldId: 'quarantine_status', operator: 'equals', value: 'Not quarantined — justification required' },
          placeholder: 'Explain why quarantine is not necessary or not feasible...',
        },
        {
          id: 'customer_notification_required',
          name: 'customerNotificationRequired',
          label: 'Customer / Regulatory Notification Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Assess whether this NCR requires customer notification or regulatory reporting (FSCA, MDR...)',
          normClause: '8.2.3',
        },
        {
          id: 'notification_details',
          name: 'notificationDetails',
          label: 'Notification Details',
          type: 'textarea',
          showIf: { fieldId: 'customer_notification_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Who was notified, when, via what channel, and what was communicated...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Investigation & Root Cause
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s5',
      order: 5,
      title: '5. Investigation & Root Cause Analysis',
      description: 'Investigate the root cause(s) of the non-conformance. Do not stop at symptoms — identify the fundamental cause.',
      normClause: 'ISO 13485 8.5.2(b)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'investigation_summary',
          name: 'investigationSummary',
          label: 'Investigation Summary',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 50 },
          helpText: 'Summarize the investigation: data reviewed, interviews conducted, tests performed, conclusions drawn.',
          normClause: '8.5.2(b)',
          placeholder: 'Investigation approach:\nData reviewed: ...\nTests performed: ...\nInterviews: ...\nKey findings: ...',
        },
        {
          id: 'rca_method',
          name: 'rcaMethod',
          label: 'Root Cause Analysis Method',
          type: 'multi_select',
          required: true,
          options: [
            '5 Whys',
            'Ishikawa Diagram (6M)',
            'Fault Tree Analysis (FTA)',
            'FMEA',
            'Laboratory Investigation',
            'Data / Trend Analysis',
            'Document Review',
            'Interviews / Observations',
            'Other',
          ],
          normClause: '8.5.2(b)',
        },
        {
          id: 'five_whys',
          name: 'fiveWhys',
          label: '5 Whys Analysis',
          type: 'repeater',
          showIf: { fieldId: 'rca_method', operator: 'contains', value: '5 Whys' },
          helpText: 'Start from the symptom (Why 1) and dig down to the root cause. Minimum 3 levels.',
          columns: [
            { id: 'why_num',    label: 'Level',  type: 'text',     required: true, width: 'sm' },
            { id: 'why_q',      label: 'Why?',   type: 'textarea', required: true, width: 'lg' },
            { id: 'why_a',      label: 'Answer',  type: 'textarea', required: true, width: 'lg' },
          ],
          minRows: 3,
          maxRows: 7,
        },
        {
          id: 'root_cause_category',
          name: 'rootCauseCategory',
          label: 'Root Cause Category (6M)',
          type: 'select',
          required: true,
          options: [
            'Manpower — Human error, training, competency',
            'Machine — Equipment failure, calibration, maintenance',
            'Method — Procedure gap, unclear instructions, wrong method',
            'Material — Raw material, component, supplier issue',
            'Measurement — Analytical error, wrong specification, instrument',
            'Environment — Temperature, humidity, contamination',
            'Management — Resources, communication, organizational',
          ],
          normClause: '8.5.2(b)',
        },
        {
          id: 'root_cause_statement',
          name: 'rootCauseStatement',
          label: 'Root Cause Statement',
          type: 'rich_text',
          required: true,
          validation: { minLength: 30 },
          helpText: 'State in one precise sentence. The root cause must explain why the NC occurred AND why it was not detected.',
          normClause: '8.5.2(b)',
          placeholder: 'The root cause is: [main causal factor] because [factual explanation]. This was not detected because [failed detection mechanism].',
        },
        {
          id: 'capa_required',
          name: 'capaRequired',
          label: 'CAPA Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Is a Corrective and Preventive Action (CAPA) needed to address this root cause?',
          normClause: '8.5.2 / 8.5.3',
        },
        {
          id: 'linked_capa_reference',
          name: 'linkedCapaReference',
          label: 'Linked CAPA Reference',
          type: 'text',
          showIf: { fieldId: 'capa_required', operator: 'equals', value: 'Yes' },
          placeholder: 'e.g. CAPA-2024-012',
          helpText: 'Reference number of the linked CAPA record',
        },
        {
          id: 'investigation_evidence',
          name: 'investigationEvidence',
          label: 'Attachments — Investigation Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png', '.docx'],
          maxFileSizeMB: 20,
          helpText: 'Analytical data, photos, chromatograms, investigation report...',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Disposition & Closure
    // ══════════════════════════════════════════════════════════════
    {
      id: 'ncr-s6',
      order: 6,
      title: '6. Disposition & Closure',
      description: 'Determine the final disposition of the non-conforming product and formally close the NCR with QA approval.',
      normClause: 'ISO 13485 8.3(c)(d)(e)',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'disposition',
          name: 'disposition',
          label: 'Disposition Decision',
          type: 'select',
          required: true,
          requiredForClosure: true,
          options: ['Use As Is', 'Rework', 'Scrap', 'Return to Supplier', 'Concession'],
          normClause: '8.3(c)',
          helpText: 'Use As Is: product meets intended purpose / Rework: can be brought into compliance / Scrap: cannot be reworked / Return to Supplier: supplier responsibility / Concession: limited acceptance with justification',
        },
        {
          id: 'disposition_justification',
          name: 'dispositionJustification',
          label: 'Disposition Justification',
          type: 'rich_text',
          required: true,
          requiredForClosure: true,
          validation: { minLength: 30 },
          helpText: 'Provide scientific and risk-based justification for the chosen disposition.',
          normClause: '8.3(c)(d)',
          placeholder: 'Justification: [rationale based on risk assessment, additional testing, impact analysis...]',
        },
        {
          id: 'rework_instructions',
          name: 'reworkInstructions',
          label: 'Rework Instructions',
          type: 'textarea',
          showIf: { fieldId: 'disposition', operator: 'equals', value: 'Rework' },
          placeholder: 'Describe the rework procedure, who will perform it, and how compliance will be verified...',
          normClause: '8.3(d)',
        },
        {
          id: 'rework_verified',
          name: 'reworkVerified',
          label: 'Rework Verification Complete?',
          type: 'yes_no_na',
          showIf: { fieldId: 'disposition', operator: 'equals', value: 'Rework' },
          helpText: 'Confirm the reworked product now meets all applicable specifications',
          normClause: '8.3(d)',
        },
        {
          id: 'concession_authorization',
          name: 'concessionAuthorization',
          label: 'Concession Authorized By',
          type: 'user_select',
          showIf: { fieldId: 'disposition', operator: 'equals', value: 'Concession' },
          helpText: 'Concessions require authorization by a designated person with appropriate authority',
          normClause: '8.3(e)',
        },
        {
          id: 'scrap_documentation',
          name: 'scrapDocumentation',
          label: 'Scrap Documentation Reference',
          type: 'text',
          showIf: { fieldId: 'disposition', operator: 'equals', value: 'Scrap' },
          placeholder: 'e.g. Destruction Certificate DC-2024-XXX',
          normClause: '8.3(c)',
        },
        {
          id: 'corrective_action_summary',
          name: 'correctiveActionSummary',
          label: 'Corrective Action Summary',
          type: 'textarea',
          placeholder: 'Brief summary of corrective actions taken to prevent recurrence...',
          normClause: '8.5.2',
        },
        {
          id: 'lessons_learned',
          name: 'lessonsLearned',
          label: 'Lessons Learned',
          type: 'textarea',
          placeholder: 'Key learnings to prevent similar non-conformances in other processes...',
          helpText: 'Optional but strongly recommended for continuous improvement (8.5.1)',
          normClause: '8.5.1',
        },
        {
          id: 'closure_evidence',
          name: 'closureEvidence',
          label: 'Attachments — Closure Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.xlsx', '.jpg', '.png'],
          maxFileSizeMB: 20,
        },
        {
          id: 'qa_approval_signature',
          name: 'qaApprovalSignature',
          label: 'QA Approval Signature — NCR Closure',
          type: 'signature',
          required: true,
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200 / 8.3',
          readOnly: false,
        },
        {
          id: 'closure_date',
          name: 'closureDate',
          label: 'Effective Closure Date',
          type: 'date',
          required: true,
          requiredForClosure: true,
          readOnly: true,
          helpText: 'Auto-filled upon QA signature',
        },
      ],
    },
  ],
};
