/**
 * training-form-template.ts
 * ──────────────────────────
 * Template Training complet conforme ISO 13485:2016 §6.2 / FDA 21 CFR 820.25 / ICH Q10
 *
 * 6 sections - 43 champs - logique conditionnelle - champs calcules
 * Base sur les pratiques reelles de l'industrie pharmaceutique et DM.
 */

import type { RichFormTemplate } from '@/types/rich-form-types';

export const TRAINING_FORM_TEMPLATE: RichFormTemplate = {
  id: 'rft-training-001',
  documentId: 'doc-tmr-training-001',
  title: 'Training Record — Competence & Awareness',
  version: '1.0',
  isActive: true,
  recordTarget: 'Training',
  normReference: 'ISO 13485:2016 §6.2 / FDA 21 CFR 820.25 / ICH Q10',
  retentionYears: 3,
  closureRequiredFields: [
    'assigned_to',
    'trainer',
    'assessment_required',
    'effectiveness_check_method',
    'effectiveness_due_date',
    'closure_signature',
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',

  sections: [

    // ══════════════════════════════════════════════════════════════
    // SECTION 1 — Training Identification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's1',
      order: 1,
      title: '1. Training Identification',
      description: 'Identify the training record, its type and the personnel involved.',
      normClause: 'ISO 13485 6.2',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'training_number',
          name: 'trainingNumber',
          label: 'Training Number',
          type: 'text',
          readOnly: true,
          helpText: 'Generated automatically',
          normClause: '4.2.4',
        },
        {
          id: 'initiation_date',
          name: 'initiationDate',
          label: 'Initiation Date',
          type: 'date',
          required: true,
          readOnly: true,
          normClause: '4.2.4',
        },
        {
          id: 'training_type',
          name: 'trainingType',
          label: 'Training Type',
          type: 'select',
          required: true,
          options: ['Onboarding', 'SOP', 'Regulatory', 'Skill', 'Certification'],
          normClause: '6.2',
        },
        {
          id: 'title',
          name: 'title',
          label: 'Training Title',
          type: 'text',
          required: true,
          validation: { minLength: 10, maxLength: 200 },
          placeholder: 'Descriptive training title (min. 10 characters)',
          normClause: '6.2',
        },
        {
          id: 'description',
          name: 'description',
          label: 'Training Description',
          type: 'textarea',
          required: true,
          helpText: 'Provide a clear and complete description of the training scope and objectives.',
          normClause: '6.2',
          placeholder: 'Describe the training objectives, scope, and expected outcomes...',
        },
        {
          id: 'regulatory_reference',
          name: 'regulatoryReference',
          label: 'Regulatory Reference',
          type: 'text',
          placeholder: 'e.g., ISO 13485 §6.2, 21 CFR 820.25',
          helpText: 'Applicable regulatory or normative reference(s) for this training',
          normClause: '6.2',
        },
        {
          id: 'category',
          name: 'category',
          label: 'Training Category',
          type: 'select',
          required: false,
          options: ['GMP', 'GLP', 'GCP', 'Safety', 'Quality', 'Other'],
          helpText: 'Select the primary quality system category this training belongs to',
        },
        {
          id: 'priority',
          name: 'priority',
          label: 'Priority',
          type: 'select',
          required: true,
          options: ['Critical', 'High', 'Medium', 'Low'],
          helpText: 'Critical = direct GxP impact — High = significant quality risk',
        },
        {
          id: 'initiated_by',
          name: 'initiatedBy',
          label: 'Initiated By',
          type: 'user_select',
          required: true,
          readOnly: true,
          helpText: 'Auto-filled from your session',
        },
        {
          id: 'assigned_to',
          name: 'assignedTo',
          label: 'Trainee',
          type: 'user_select',
          required: true,
          normClause: '6.2',
          helpText: 'The person who will receive this training',
        },
        {
          id: 'target_completion_date',
          name: 'targetCompletionDate',
          label: 'Target Completion Date',
          type: 'date',
          required: true,
          normClause: '6.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 2 — Content & Materials
    // ══════════════════════════════════════════════════════════════
    {
      id: 's2',
      order: 2,
      title: '2. Content & Materials',
      description: 'Describe the training content, delivery method and associated materials.',
      normClause: 'ISO 13485 6.2(b)',
      collapsible: true,
      defaultCollapsed: false,
      fields: [
        {
          id: 'linked_document_id',
          name: 'linkedDocumentId',
          label: 'Linked Document Number',
          type: 'text',
          placeholder: 'Document number linked to training',
          helpText: 'SOP, WI, or other controlled document that is the subject of this training',
          normClause: '4.2.3',
        },
        {
          id: 'materials_description',
          name: 'materialsDescription',
          label: 'Training Materials Description',
          type: 'textarea',
          helpText: 'List training materials, presentations, handouts...',
          placeholder: 'e.g., SOP-PROD-001 v3.2, Presentation deck, Handout #42, Video module...',
          normClause: '6.2(b)',
        },
        {
          id: 'duration',
          name: 'duration',
          label: 'Duration',
          type: 'text',
          placeholder: 'e.g., 2 hours, 3 days',
          helpText: 'Estimated total duration of the training session',
        },
        {
          id: 'delivery_method',
          name: 'deliveryMethod',
          label: 'Delivery Method',
          type: 'select',
          required: false,
          options: ['Classroom', 'Online/Self-paced', 'On-the-Job', 'Webinar', 'Blended'],
          normClause: '6.2(b)',
        },
        {
          id: 'training_location',
          name: 'trainingLocation',
          label: 'Training Location',
          type: 'text',
          placeholder: 'Room, building, or virtual link',
          helpText: 'Physical room/building or virtual meeting link',
        },
        {
          id: 'prerequisite_training',
          name: 'prerequisiteTraining',
          label: 'Prerequisite Training',
          type: 'text',
          placeholder: 'Required prior training before enrollment',
          helpText: 'Training records or competencies the trainee must have completed before attending',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 3 — Trainer & Schedule
    // ══════════════════════════════════════════════════════════════
    {
      id: 's3',
      order: 3,
      title: '3. Trainer & Schedule',
      description: 'Assign the trainer, define the schedule and determine if retraining is required.',
      normClause: 'ISO 13485 6.2',
      collapsible: true,
      fields: [
        {
          id: 'trainer',
          name: 'trainer',
          label: 'Trainer',
          type: 'user_select',
          required: true,
          normClause: '6.2',
          helpText: 'Qualified person delivering the training',
        },
        {
          id: 'trainer_qualifications',
          name: 'trainerQualifications',
          label: 'Trainer Qualifications',
          type: 'textarea',
          showIf: { fieldId: 'trainer', operator: 'is_filled' },
          helpText: 'Describe the trainer\'s qualifications, certifications and relevant experience',
          placeholder: 'e.g., Certified GMP Trainer, 10 years QA experience, ISO 13485 Lead Auditor...',
          normClause: '6.2',
        },
        {
          id: 'scheduled_date',
          name: 'scheduledDate',
          label: 'Scheduled Start Date',
          type: 'date',
          helpText: 'Planned start date of the training session',
        },
        {
          id: 'scheduled_end_date',
          name: 'scheduledEndDate',
          label: 'Scheduled End Date',
          type: 'date',
          helpText: 'Planned end date (same as start date for single-day sessions)',
        },
        {
          id: 'retraining_required',
          name: 'retrainingRequired',
          label: 'Retraining Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Indicate whether periodic retraining is required to maintain competence',
          normClause: '6.2',
        },
        {
          id: 'retraining_interval',
          name: 'retrainingInterval',
          label: 'Retraining Interval',
          type: 'select',
          showIf: { fieldId: 'retraining_required', operator: 'equals', value: 'Yes' },
          options: ['6 months', '12 months', '24 months', '36 months'],
          helpText: 'Frequency at which retraining must occur to maintain qualification',
          normClause: '6.2',
        },
        {
          id: 'retraining_justification',
          name: 'retrainingJustification',
          label: 'Retraining Justification',
          type: 'textarea',
          showIf: { fieldId: 'retraining_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Justify why periodic retraining is required and the chosen interval...',
          helpText: 'Explain the rationale for the retraining frequency based on risk and regulatory requirements',
          normClause: '6.2',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 4 — Competency Assessment
    // ══════════════════════════════════════════════════════════════
    {
      id: 's4',
      order: 4,
      title: '4. Competency Assessment',
      description: 'Define how competency will be evaluated and the acceptance criteria for passing.',
      normClause: 'ISO 13485 6.2(a)',
      requiredForClosure: true,
      collapsible: true,
      fields: [
        {
          id: 'assessment_required',
          name: 'assessmentRequired',
          label: 'Assessment Required?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Indicate whether a formal competency assessment is required for this training',
          normClause: '6.2(a)',
        },
        {
          id: 'assessment_method',
          name: 'assessmentMethod',
          label: 'Assessment Method',
          type: 'select',
          showIf: { fieldId: 'assessment_required', operator: 'equals', value: 'Yes' },
          options: [
            'Written Exam',
            'Practical Demonstration',
            'Oral Assessment',
            'Observation',
            'Combined (Written + Practical)',
          ],
          helpText: 'Select the method used to evaluate trainee competency',
          normClause: '6.2(a)',
        },
        {
          id: 'passing_score',
          name: 'passingScore',
          label: 'Passing Score (%)',
          type: 'number',
          showIf: { fieldId: 'assessment_required', operator: 'equals', value: 'Yes' },
          validation: { min: 0, max: 100 },
          placeholder: 'e.g., 80',
          helpText: 'Minimum score required to pass the assessment (0-100)',
          normClause: '6.2(a)',
        },
        {
          id: 'assessment_criteria',
          name: 'assessmentCriteria',
          label: 'Assessment Criteria',
          type: 'textarea',
          showIf: { fieldId: 'assessment_required', operator: 'equals', value: 'Yes' },
          placeholder: 'Define measurable acceptance criteria...',
          helpText: 'Define measurable, objective acceptance criteria for competency determination',
          normClause: '6.2(a)',
        },
        {
          id: 'practical_assessment_details',
          name: 'practicalAssessmentDetails',
          label: 'Practical Assessment Details',
          type: 'textarea',
          showIf: { fieldId: 'assessment_method', operator: 'contains', value: 'Practical' },
          placeholder: 'Describe the practical demonstration tasks, expected outcomes and evaluation checklist...',
          helpText: 'Detail the practical tasks the trainee must perform and the evaluation checklist',
          normClause: '6.2(a)',
        },
        {
          id: 'remedial_action',
          name: 'remedialAction',
          label: 'Remedial Action (if failed)',
          type: 'textarea',
          showIf: { fieldId: 'assessment_required', operator: 'equals', value: 'Yes' },
          placeholder: 'What happens if trainee fails the assessment?',
          helpText: 'Describe the remedial process: retraining, re-assessment timeline, escalation to manager, etc.',
          normClause: '6.2(a)',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 5 — Compliance & Certification
    // ══════════════════════════════════════════════════════════════
    {
      id: 's5',
      order: 5,
      title: '5. Compliance & Certification',
      description: 'Document regulatory compliance, certification requirements and data integrity aspects.',
      normClause: 'ISO 13485 6.2 / 21 CFR 820.25',
      collapsible: true,
      fields: [
        {
          id: 'requires_certification',
          name: 'requiresCertification',
          label: 'Requires Certification?',
          type: 'yes_no_na',
          required: true,
          helpText: 'Does this training result in a formal certification or qualification?',
          normClause: '6.2',
        },
        {
          id: 'certification_validity',
          name: 'certificationValidity',
          label: 'Certification Validity Period',
          type: 'select',
          showIf: { fieldId: 'requires_certification', operator: 'equals', value: 'Yes' },
          options: ['1 year', '2 years', '3 years', '5 years', 'Indefinite'],
          helpText: 'Period for which the certification remains valid before renewal is required',
          normClause: '6.2',
        },
        {
          id: 'applicable_standards',
          name: 'applicableStandards',
          label: 'Applicable Standards',
          type: 'multi_select',
          options: [
            'ISO 13485',
            '21 CFR 820',
            'ICH Q10',
            'EU MDR 2017/745',
            'cGMP',
            'GLP',
            'GCP',
            'Other',
          ],
          helpText: 'Select all regulatory standards applicable to this training',
          normClause: '6.2 / 820.25',
        },
        {
          id: 'data_integrity_awareness',
          name: 'dataIntegrityAwareness',
          label: 'Data Integrity Awareness (ALCOA+)',
          type: 'checkbox',
          helpText: 'Training includes ALCOA+ data integrity principles',
          normClause: '21 CFR 11.10',
        },
        {
          id: 'gxp_relevance',
          name: 'gxpRelevance',
          label: 'GxP Relevance',
          type: 'select',
          required: false,
          options: ['GxP Critical', 'GxP Related', 'Non-GxP'],
          helpText: 'Classify the GxP relevance of this training for risk-based prioritization',
          normClause: '6.2',
        },
        {
          id: 'audit_trail_required',
          name: 'auditTrailRequired',
          label: 'Audit Trail Required',
          type: 'checkbox',
          helpText: 'Check if this training record must maintain a full audit trail per 21 CFR Part 11',
          normClause: '4.2.4',
        },
        {
          id: 'training_attachments',
          name: 'trainingAttachments',
          label: 'Attachments — Training Materials & Evidence',
          type: 'file',
          acceptedFormats: ['.pdf', '.pptx', '.xlsx', '.docx', '.jpg', '.png'],
          maxFileSizeMB: 25,
          helpText: 'Upload training materials, attendance sheets, exam papers, certificates...',
          normClause: '4.2.4',
        },
      ],
    },

    // ══════════════════════════════════════════════════════════════
    // SECTION 6 — Review & Approval
    // ══════════════════════════════════════════════════════════════
    {
      id: 's6',
      order: 6,
      title: '6. Review & Approval',
      description: 'Verify training effectiveness, collect feedback and close the training record with electronic signature.',
      normClause: 'ISO 13485 6.2 / 21 CFR Part 11',
      requiredForClosure: true,
      collapsible: false,
      fields: [
        {
          id: 'training_coordinator_review',
          name: 'trainingCoordinatorReview',
          label: 'Training Coordinator Review',
          type: 'user_select',
          requiredForClosure: true,
          helpText: 'Training coordinator responsible for reviewing and approving this record',
          normClause: '6.2',
        },
        {
          id: 'effectiveness_check_method',
          name: 'effectivenessCheckMethod',
          label: 'Effectiveness Check Method',
          type: 'select',
          requiredForClosure: true,
          options: [
            'Post-training quiz',
            'On-the-job observation',
            'KPI monitoring',
            'Manager attestation',
            'Follow-up audit',
          ],
          helpText: 'Method used to verify that training was effective and competence was achieved',
          normClause: '6.2(a)',
        },
        {
          id: 'effectiveness_due_date',
          name: 'effectivenessDueDate',
          label: 'Effectiveness Check Due Date',
          type: 'date',
          requiredForClosure: true,
          helpText: 'Date by which the effectiveness check must be completed',
          normClause: '6.2(a)',
        },
        {
          id: 'lessons_learned',
          name: 'lessonsLearned',
          label: 'Lessons Learned',
          type: 'textarea',
          placeholder: 'Feedback, improvements for future sessions...',
          helpText: 'Capture feedback and improvements for future training sessions',
          normClause: '8.5.1',
        },
        {
          id: 'closure_signature',
          name: 'closureSignature',
          label: 'Closure Signature — Training Record',
          type: 'signature',
          requiredForClosure: true,
          helpText: 'Electronic signature per 21 CFR Part 11. Your password will be verified against your account.',
          normClause: '21 CFR 11.200',
          readOnly: false,
        },
        {
          id: 'closure_date',
          name: 'closureDate',
          label: 'Effective Closure Date',
          type: 'date',
          readOnly: true,
          requiredForClosure: true,
          helpText: 'Auto-filled upon closure signature',
        },
      ],
    },
  ],
};
